export const data = [
  {
    name: "AKI",
    img: "/img/AKI.webp",
    imgActive: "/img/AKIA.webp",
    imgNotActive: "/img/AKIN.webp",
    describe:
      "A poison-wielding apprentice of F.A.N.G, the former Shadaloo officer.Enchanted by the power of toxins, nothing brings her more joy than testing them on a new target—other than attention from her “master,” that is.",
    hates: "Nice weather, and anyone but her master",
    likes: "Snakes, rain, Master F.A.N.G",
    height: "5'8",
    weight: "126 lbs",
    img1: "/img/O_AKI_1.webp",
    img2: "/img/O_AKI_2.webp",
    out1: [
      "/img/AKIF_01.webp",
      "/img/AKIF_02.webp",
      "/img/AKIF_03.webp",
      "/img/AKIF_04.webp",
      "/img/AKIF_05.webp",
      "/img/AKIF_06.webp",
      "/img/AKIF_07.webp",
      "/img/AKIF_08.webp",
      "/img/AKIF_09.webp",
      "/img/AKIF_10.webp",
    ],
    out2: [
      "/img/AKIS_01.webp",
      "/img/AKIS_02.webp",
      "/img/AKIS_03.webp",
      "/img/AKIS_04.webp",
      "/img/AKIS_05.webp",
      "/img/AKIS_06.webp",
      "/img/AKIS_07.webp",
      "/img/AKIS_08.webp",
      "/img/AKIS_09.webp",
      "/img/AKIS_10.webp",
    ],
    video: [
      {
        characterName: "AKI",
        comboName: "Nightshade Pulse",
        video: "/img/V_AKI_1.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Nightshade Chaser",
        video: "/img/V_AKI_2.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Orchid Spring",
        video: "/img/V_AKI_3.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Toxic Wreath",
        video: "/img/V_AKI_4.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Serpent Lash",
        video: "/img/V_AKI_5.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Cruel Fate",
        video: "/img/V_AKI_6.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Snake Step",
        video: "/img/V_AKI_7.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Sinister Slide",
        video: "/img/V_AKI_8.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Venomous Fang",
        video: "/img/V_AKI_9.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Heel Strike",
        video: "/img/V_AKI_10.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Entrapment",
        video: "/img/V_AKI_11.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Deadly Implication",
        video: "/img/V_AKI_12.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Tainted Talons",
        video: "/img/V_AKI_13.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Claws of Ya Zi",
        video: "/img/V_AKI_14.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Pu Lao",
        video: "/img/V_AKI_15.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Chi Wen",
        video: "/img/V_AKI_16.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Qiu Niu",
        video: "/img/V_AKI_17.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Gong Fu",
        video: "/img/V_AKI_18.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Hun Dun",
        video: "/img/V_AKI_19.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Qiong Qi",
        video: "/img/V_AKI_20.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Whisper",
        video: "/img/V_AKI_21.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Gluttony",
        video: "/img/V_AKI_22.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Drive Impact: Zao Chi",
        video: "/img/V_AKI_23.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Drive Reversal: Feng Shi",
        video: "/img/V_AKI_24.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Drive Parry",
        video: "/img/V_AKI_25.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Parry Drive Rush",
        video: "/img/V_AKI_26.mp4",
      },
      {
        characterName: "AKI",
        comboName: "Cancel Drive Rush",
        video: "/img/V_AKI_27.mp4",
      },
    ],
    special: [
      {
        characterName: "AKI",
        comboName: "Nightshade Pulse",
        img: "/img/C_AKI_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "AKI",
        comboName: "Nightshade Chaser",
        img: "/img/C_AKI_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "AKI",
        comboName: "Orchid Spring",
        img: "/img/C_AKI_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "AKI",
        comboName: "Toxic Wreath",
        img: "/img/C_AKI_4.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "AKI",
        comboName: "Serpent Lash",
        img: "/img/C_AKI_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "AKI",
        comboName: "Cruel Fate",
        left: 1,
        img: "/img/C_AKI_6.webp",
        arrows: ["/img/Punch.webp"],
      },
      {
        characterName: "AKI",
        comboName: "Snake Step",
        left: 1,
        img: "/img/C_AKI_7.webp",
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "AKI",
        comboName: "Sinister Slide",
        left: 1,
        img: "/img/C_AKI_8.webp",
        arrows: ["/img/D.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "AKI",
        comboName: "Venomous Fang",
        left: 1,
        img: "/img/C_AKI_9.webp",
        arrows: [
          "/img/Punch.webp",
          "/img/L.webp",
          "/img/Kick.webp",
          "/img/L.webp",
        ],
      },
      {
        characterName: "AKI",
        comboName: "Heel Strike",
        left: 2,
        img: "/img/C_AKI_10.webp",
        arrows: ["/img/Punch.webp"],
      },
      {
        characterName: "AKI",
        comboName: "Entrapment",
        img: "/img/C_AKI_11.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    supel: [
      {
        characterName: "AKI",
        comboName: "Deadly Implication",
        img: "/img/C_AKI_12.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "AKI",
        comboName: "Tainted Talons",
        img: "/img/C_AKI_13.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "AKI",
        comboName: "Claws of Ya Zi",
        img: "/img/C_AKI_14.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "AKI",
        comboName: "Pu Lao",
        img: "/img/C_AKI_15.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "AKI",
        comboName: "Chi Wen",
        img: "/img/C_AKI_16.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "AKI",
        comboName: "Qiu Niu",
        img: "/img/C_AKI_17.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "AKI",
        comboName: "Gong Fu",
        img: "/img/C_AKI_18.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "AKI",
        comboName: "Hun Dun",
        img: "/img/C_AKI_19.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/Punch.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "AKI",
        comboName: "Qiong Qi",
        img: "/img/C_AKI_20.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    throws: [
      {
        characterName: "AKI",
        comboName: "Whisper",
        img: "/img/C_AKI_21.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/L.webp",
          "/img/Punch.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "AKI",
        comboName: "Gluttony",
        img: "/img/C_AKI_22.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/Punch.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
    ],
    common: [
      {
        characterName: "AKI",
        comboName: "Drive Impact: Zao Chi",
        img: "/img/C_AKI_23.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/Punch.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "AKI",
        comboName: "Drive Reversal: Feng Shi",
        img: "/img/C_AKI_24.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Punch.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "AKI",
        comboName: "Drive Parry",
        img: "/img/C_AKI_25.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/Punch.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "AKI",
        comboName: "Parry Drive Rush",
        left: 2,
        img: "/img/C_AKI_26.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "AKI",
        comboName: "Cancel Drive Rush",
        img: "/img/C_AKI_27.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
