export const data = [
  {
    name: "Blanka",
    zoom: 1,
    main: 7,
    img: "/test",
    imgActive: "/img/BlankaA.webp",
    imgNotActive: "/img/BlankaN.webp",
    describe:
      "A kindhearted defender of nature, Blanka has become an adventure tour guide, confident his intimate knowledge of the jungle will serve as a springboard to fame—and a comfortable life for his beloved mother.",
    hates: "Army ants",
    likes: "Samantha, Blanka-chan dolls",
    height: "6'4",
    weight: "216 lbs",
    img1: "/img/O_Blanka_1.webp",
    img2: "/img/O_Blanka_2.webp",
    out1: [
      "/img/BlankaF_01.webp",
      "/img/BlankaF_02.webp",
      "/img/BlankaF_03.webp",
      "/img/BlankaF_04.webp",
      "/img/BlankaF_05.webp",
      "/img/BlankaF_06.webp",
      "/img/BlankaF_07.webp",
      "/img/BlankaF_08.webp",
      "/img/BlankaF_09.webp",
    ],
    out2: [
      "/img/BlankaS_01.webp",
      "/img/BlankaS_02.webp",
      "/img/BlankaS_03.webp",
      "/img/BlankaS_04.webp",
      "/img/BlankaS_05.webp",
      "/img/BlankaS_06.webp",
      "/img/BlankaS_07.webp",
      "/img/BlankaS_08.webp",
      "/img/BlankaS_09.webp",
      "/img/BlankaS_10.webp",
    ],
    video: [
      {
        characterName: "Blanka",
        comboName: "Electric Thunder",
        video: "/img/V_Blanka_1.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Rolling Attact",
        video: "/img/V_Blanka_2.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Vertical Rolling Attack",
        video: "/img/V_Blanka_3.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Backstep Rolling",
        video: "/img/V_Blanka_4.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Aerial Rolling Attack",
        video: "/img/V_Blanka_5.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Wild Hunt",
        video: "/img/V_Blanka_6.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Blanka-chan Bomb",
        video: "/img/V_Blanka_7.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Rolling Cannon",
        video: "/img/V_Blanka_8.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Shout of Earth",
        video: "/img/V_Blanka_9.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Lightning Beast",
        video: "/img/V_Blanka_10.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Ground Shave Cannonball",
        video: "/img/V_Blanka_11.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Rock Crushe",
        video: "/img/V_Blanka_12.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Double Knee Bombs",
        video: "/img/V_Blanka_13.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Wild Edge",
        video: "/img/V_Blanka_14.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Wild Nail",
        video: "/img/V_Blanka_15.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Amazon River Run",
        video: "/img/V_Blanka_16.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Coward Crouch",
        video: "/img/V_Blanka_17.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Wild Lift",
        video: "/img/V_Blanka_18.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Raid Jump",
        video: "/img/V_Blanka_19.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Surprise Forward Hop",
        video: "/img/V_Blanka_20.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Surprise Back Hop",
        video: "/img/V_Blanka_21.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Wild Fang",
        video: "/img/V_Blanka_22.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Jungle Flip",
        video: "/img/V_Blanka_23.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Wild Bites",
        video: "/img/V_Blanka_24.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Drive Impact Wild Scratch",
        video: "/img/V_Blanka_25.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Drive Reversal Quick Rolling",
        video: "/img/V_Blanka_26.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Drive Parry",
        video: "/img/V_Blanka_27.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Parry Drive Rush",
        video: "/img/V_Blanka_28.mp4",
      },
      {
        characterName: "Blanka",
        comboName: "Cancel Drive Rush",
        video: "/img/V_Blanka_29.mp4",
      },
    ],
    special: [
      {
        characterName: "Blanka",
        comboName: "Electric Thunder",
        img: "/img/C_Blanka_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Rolling Attact",
        img: "/img/C_Blanka_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/L.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Vertical Rolling Attack",
        img: "/img/C_Blanka_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Up.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Backstep Rolling",
        img: "/img/C_Blanka_4.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Dr.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Aerial Rolling Attack",
        img: "/img/C_Blanka_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/L.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Wild Hunt",
        img: "/img/C_Blanka_6.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Blanka-chan Bomb",
        img: "/img/C_Blanka_7.webp",
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Rolling Cannon",
        img: "/img/C_Blanka_8.webp",
        arrows: ["/img/Punch.webp"],
      },
    ],
    supel: [
      {
        characterName: "Blanka",
        comboName: "Shout of Earth",
        img: "/img/C_Blanka_9.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Lightning Beast",
        img: "/img/C_Blanka_10.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Ground Shave Cannonball",
        img: "/img/C_Blanka_11.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Blanka",
        comboName: "Rock Crushe",
        img: "/img/C_Blanka_12.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Blanka",
        comboName: "Double Knee Bombs",
        img: "/img/C_Blanka_13.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Blanka",
        comboName: "Wild Edge",
        img: "/img/C_Blanka_14.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Blanka",
        comboName: "Wild Nail",
        img: "/img/C_Blanka_15.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Blanka",
        comboName: "Amazon River Run",
        img: "/img/C_Blanka_16.webp",
        arrows: ["/img/Dr.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Blanka",
        comboName: "Coward Crouch",
        img: "/img/C_Blanka_17.webp",
        arrows: [
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Wild Lift",
        left: 1,
        img: "/img/C_Blanka_18.webp",
        arrows: ["/img/Punch.webp"],
      },
      {
        characterName: "Blanka",
        comboName: "Raid Jump",
        left: 2,
        img: "/img/C_Blanka_19.webp",
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Blanka",
        comboName: "Surprise Forward Hop",
        img: "/img/C_Blanka_20.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Surprise Back Hop",
        img: "/img/C_Blanka_21.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    throws: [
      {
        characterName: "Blanka",
        comboName: "Wild Fang",
        img: "/img/C_Blanka_22.webp",
        arrows: [
          "/img/N.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Jungle Flip",
        img: "/img/C_Blanka_23.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Wild Bites",
        img: "/img/C_Blanka_24.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
    ],
    common: [
      {
        characterName: "Blanka",
        comboName: "Drive Impact Wild Scratch",
        img: "/img/C_Blanka_25.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Blanka",
        comboName: "Drive Reversal Quick Rolling",
        img: "/img/C_Blanka_26.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Blanka",
        comboName: "Drive Parry",
        img: "/img/C_Blanka_27.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Blanka",
        comboName: "Parry Drive Rush",
        img: "/img/C_Blanka_28.webp",
        left: 2,
        energy: "/img/E_0,5.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Blanka",
        comboName: "Cancel Drive Rush",
        img: "/img/C_Blanka_29.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
