export const data = [
  {
    name: "Cammy",
    img: "/img/Cammy.webp",
    imgActive: "/img/CammyA.webp",
    imgNotActive: "/img/CammyN.webp",
    describe:
      "Member of British special forces unit Delta Red. Distinguished herself in the operation against Shadaloo, with which she shares a fated connection. Hyper-competent but somewhat moody. Currently working at HQ.",
    hates: "Everything (if she's grumpy)",
    likes: "Cats",
    height: "5'5",
    weight: "134 lbs",
    img1: "/img/O_Cammy_1.webp",
    img2: "/img/O_Cammy_2.webp",
    out1: [
      "/img/CammyF_01.webp",
      "/img/CammyF_02.webp",
      "/img/CammyF_03.webp",
      "/img/CammyF_04.webp",
      "/img/CammyF_05.webp",
      "/img/CammyF_06.webp",
      "/img/CammyF_07.webp",
      "/img/CammyF_08.webp",
      "/img/CammyF_09.webp",
    ],
    out2: [
      "/img/CammyS_01.webp",
      "/img/CammyS_02.webp",
      "/img/CammyS_03.webp",
      "/img/CammyS_04.webp",
      "/img/CammyS_05.webp",
      "/img/CammyS_06.webp",
      "/img/CammyS_07.webp",
      "/img/CammyS_08.webp",
      "/img/CammyS_09.webp",
      "/img/CammyS_10.webp",
    ],
    video: [
      {
        characterName: "Cammy",
        comboName: "Spiral Arrow",
        video: "/img/V_Cammy_1.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Cannon Spike",
        video: "/img/V_Cammy_2.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Quick Spin Knuckle",
        video: "/img/V_Cammy_3.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Cannon Strike",
        video: "/img/V_Cammy_4.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Hooligan Combination",
        video: "/img/V_Cammy_5.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Razors Edge Slicer",
        video: "/img/V_Cammy_6.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Cannonn Strike",
        video: "/img/V_Cammy_7.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Reverse Edge",
        video: "/img/V_Cammy_8.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Fatal Leg Twister",
        video: "/img/V_Cammy_9.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Silent Step",
        video: "/img/V_Cammy_10.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Spin Drive Smasher",
        video: "/img/V_Cammy_11.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Killer Bee Spin",
        video: "/img/V_Cammy_12.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Aerial Killer Bee Spin",
        video: "/img/V_Cammy_13.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Delta Red Assault",
        video: "/img/V_Cammy_14.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Lift Uppercut",
        video: "/img/V_Cammy_15.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Delayed Ripper",
        video: "/img/V_Cammy_16.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Assault Blade",
        video: "/img/V_Cammy_17.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Lift Combination",
        video: "/img/V_Cammy_18.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Swing Combination",
        video: "/img/V_Cammy_19.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Rough Landing",
        video: "/img/V_Cammy_20.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Dalta Throw",
        video: "/img/V_Cammy_21.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Leg Scissors Choke",
        video: "/img/V_Cammy_22.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Drive Impact Spin Raider",
        video: "/img/V_Cammy_23.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Drive Reversal Countersnipe",
        video: "/img/V_Cammy_24.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Drive Parry",
        video: "/img/V_Cammy_25.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Parry Drive Rush",
        video: "/img/V_Cammy_26.mp4",
      },
      {
        characterName: "Cammy",
        comboName: "Cancel Drive Rush",
        video: "/img/V_Cammy_27.mp4",
      },
    ],
    special: [
      {
        characterName: "Cammy",
        comboName: "Spiral Arrow",
        img: "/img/C_Cammy_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Cammy",
        comboName: "Cannon Spike",
        img: "/img/C_Cammy_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Cammy",
        comboName: "Quick Spin Knuckle",
        img: "/img/C_Cammy_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Cammy",
        comboName: "Cannon Strike",
        img: "/img/C_Cammy_4.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Cammy",
        comboName: "Hooligan Combination",
        img: "/img/C_Cammy_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Cammy",
        comboName: "Razors Edge Slicer",
        left: 1,
        img: "/img/C_Cammy_6.webp",
        arrows: ["/img/Punch.webp"],
      },
      {
        characterName: "Cammy",
        comboName: "Cannonn Strike",
        left: 1,
        img: "/img/C_Cammy_7.webp",
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Cammy",
        comboName: "Reverse Edge",
        left: 1,
        img: "/img/C_Cammy_8.webp",
        arrows: ["/img/D.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Cammy",
        comboName: "Fatal Leg Twister",
        left: 1,
        img: "/img/C_Cammy_9.webp",
        arrows: [
          "/img/Punch.webp",
          "/img/L.webp",
          "/img/Kick.webp",
          "/img/L.webp",
        ],
      },
      {
        characterName: "Cammy",
        comboName: "Silent Step",
        left: 2,
        img: "/img/C_Cammy_10.webp",
        arrows: ["/img/Punch.webp"],
      },
    ],
    supel: [
      {
        characterName: "Cammy",
        comboName: "Spin Drive Smasher",
        img: "/img/C_Cammy_11.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Cammy",
        comboName: "Killer Bee Spin",
        img: "/img/C_Cammy_12.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Cammy",
        comboName: "Aerial Killer Bee Spin",
        img: "/img/C_Cammy_13.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Cammy",
        comboName: "Delta Red Assault",
        img: "/img/C_Cammy_14.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Cammy",
        comboName: "Lift Uppercut",
        img: "/img/C_Cammy_15.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Cammy",
        comboName: "Delayed Ripper",
        img: "/img/C_Cammy_16.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Cammy",
        comboName: "Assault Blade",
        img: "/img/C_Cammy_17.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Cammy",
        comboName: "Lift Combination",
        img: "/img/C_Cammy_18.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Cammy",
        comboName: "Swing Combination",
        img: "/img/C_Cammy_19.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/Punch.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
    ],
    throws: [
      {
        characterName: "Cammy",
        comboName: "Rough Landing",
        img: "/img/C_Cammy_20.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Cammy",
        comboName: "Dalta Throw",
        img: "/img/C_Cammy_21.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/L.webp",
          "/img/Punch.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Cammy",
        comboName: "Leg Scissors Choke",
        img: "/img/C_Cammy_22.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/Punch.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
    ],
    common: [
      {
        characterName: "Cammy",
        comboName: "Drive Impact Spin Raider",
        img: "/img/C_Cammy_23.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/Punch.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Cammy",
        comboName: "Drive Reversal Countersnipe",
        img: "/img/C_Cammy_24.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Punch.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Cammy",
        comboName: "Drive Parry",
        img: "/img/C_Cammy_25.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/Punch.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Cammy",
        comboName: "Parry Drive Rush",
        left: 2,
        img: "/img/C_Cammy_26.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Cammy",
        comboName: "Cancel Drive Rush",
        img: "/img/C_Cammy_27.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
