export const data = [
  {
    name: "Chun",
    zoom: 5,
    main: 6,
    imgActive: "/img/ChunA.webp",
    imgNotActive: "/img/ChunN.webp",
    describe:
      "A former high-kicking ICPO agent, Chun-Li looks after Li-Fen, a victim of the Black Moon Incident. With Shadaloo sundered, she now runs kung fu classes, and has become a well-loved member of the local community.",
    hates: "Crime, indecisiveness",
    likes: "Days off, shopping with Li-Fen",
    height: "5'7",
    weight: "Secret♡",
    img1: "/img/O_Chun_1.webp",
    img2: "/img/O_Chun_2.webp",
    out1: [
      "/img/ChunF_01.webp",
      "/img/ChunF_02.webp",
      "/img/ChunF_03.webp",
      "/img/ChunF_04.webp",
      "/img/ChunF_05.webp",
      "/img/ChunF_06.webp",
      "/img/ChunF_07.webp",
      "/img/ChunF_08.webp",
      "/img/ChunF_09.webp",
    ],
    out2: [
      "/img/ChunS_01.webp",
      "/img/ChunS_02.webp",
      "/img/ChunS_03.webp",
      "/img/ChunS_04.webp",
      "/img/ChunS_05.webp",
      "/img/ChunS_06.webp",
      "/img/ChunS_07.webp",
      "/img/ChunS_08.webp",
      "/img/ChunS_09.webp",
      "/img/ChunS_10.webp",
    ],
    video: [
      {
        characterName: "Chun",
        comboName: "Kikolen",
        video: "/img/V_Chun_1.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Hundred Lightning Kicks",
        video: "/img/V_Chun_2.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Lightning Kick Barrage",
        video: "/img/V_Chun_3.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Aerial Hundred Lightning Kicks",
        video: "/img/V_Chun_4.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Spinning Bird Kick",
        video: "/img/V_Chun_5.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Hazanshu",
        video: "/img/V_Chun_6.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Tensho Kicks",
        video: "/img/V_Chun_7.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Kikosho",
        video: "/img/V_Chun_8.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Aerial Kikosho",
        video: "/img/V_Chun_9.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Hoyoku-sen",
        video: "/img/V_Chun_10.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Soten Ranka",
        video: "/img/V_Chun_11.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Swift Thrust",
        video: "/img/V_Chun_12.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Hakkei",
        video: "/img/V_Chun_13.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Water Lotus Fish",
        video: "/img/V_Chun_14.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Yokusen Kick",
        video: "/img/V_Chun_15.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Falling Crane",
        video: "/img/V_Chun_16.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Yoso Kick",
        video: "/img/V_Chun_17.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Wall Jump",
        video: "/img/V_Chun_18.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Soaring Eagle Punches",
        video: "/img/V_Chun_19.mp4",
      },
      {
        video: "/img/V_Chun_20.mp4",
        characterName: "Chun",
        comboName: "Serenity Stream",
      },
      {
        characterName: "Chun",
        comboName: "Orchid Palm",
        video: "/img/V_Chun_21.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Snake Strike",
        video: "/img/V_Chun_22.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Lotus Fist",
        video: "/img/V_Chun_23.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Forward Strike",
        video: "/img/V_Chun_24.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Senpu Kick",
        video: "/img/V_Chun_25.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Tenku Kick",
        video: "/img/V_Chun_26.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Koshuto",
        video: "/img/V_Chun_27.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Taiji Fan",
        video: "/img/V_Chun_28.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Ryuseraku",
        video: "/img/V_Chun_29.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Drive Reversal Hoyoku Kick",
        video: "/img/V_Chun_30.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Drive Impact Hosen Kick",
        video: "/img/V_Chun_31.mp4",
      },
      {
        video: "/img/V_Chun_32.mp4",
        characterName: "Chun",
        comboName: "Drive Parry",
      },
      {
        characterName: "Chun",
        comboName: "Parry Drive Rush",
        video: "/img/V_Chun_33.mp4",
      },
      {
        characterName: "Chun",
        comboName: "Cancel Drive Rush",
        video: "/img/V_Chun_34.mp4",
      },
    ],
    special: [
      {
        characterName: "Chun",
        comboName: "Kikolen",
        img: "/img/C_Chun_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/L.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Chun",
        comboName: "Hundred Lightning Kicks",
        img: "/img/C_Chun_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Chun",
        comboName: "Lightning Kick Barrage",
        left: 2,
        img: "/img/C_Chun_3.webp",
        arrows: ["/img/Kick.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Aerial Hundred Lightning Kicks",
        img: "/img/C_Chun_4.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Chun",
        comboName: "Spinning Bird Kick",
        img: "/img/C_Chun_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Up.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Chun",
        comboName: "Hazanshu",
        img: "/img/C_Chun_6.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Chun",
        comboName: "Tensho Kicks",
        img: "/img/C_Chun_7.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    supel: [
      {
        characterName: "Chun",
        comboName: "Kikosho",
        img: "/img/C_Chun_8.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Chun",
        comboName: "Aerial Kikosho",
        img: "/img/C_Chun_9.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Chun",
        comboName: "Hoyoku-sen",
        img: "/img/C_Chun_10.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Chun",
        comboName: "Soten Ranka",
        img: "/img/C_Chun_11.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Chun",
        comboName: "Swift Thrust",
        img: "/img/C_Chun_12.webp",
        arrows: [
          "/img/L.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Chun",
        comboName: "Hakkei",
        img: "/img/C_Chun_13.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Water Lotus Fish",
        img: "/img/C_Chun_14.webp",
        arrows: ["/img/Dr.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Yokusen Kick",
        img: "/img/C_Chun_15.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Falling Crane",
        img: "/img/C_Chun_16.webp",
        arrows: ["/img/Dr.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Yoso Kick",
        img: "/img/C_Chun_17.webp",
        arrows: ["/img/D.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Wall Jump",
        img: "/img/C_Chun_18.webp",
        arrows: ["/img/UpR.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Soaring Eagle Punches",
        img: "/img/C_Chun_19.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Serenity Stream",
        img: "/img/C_Chun_20.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Chun",
        comboName: "Orchid Palm",
        left: 1,
        img: "/img/C_Chun_21.webp",
        arrows: ["/img/Punch.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Snake Strike",
        left: 1,
        img: "/img/C_Chun_22.webp",
        arrows: ["/img/Punch.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Lotus Fist",
        left: 1,
        img: "/img/C_Chun_23.webp",
        arrows: ["/img/Punch.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Forward Strike",
        left: 1,
        img: "/img/C_Chun_24.webp",
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Senpu Kick",
        left: 1,
        img: "/img/C_Chun_25.webp",
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Tenku Kick",
        left: 2,
        img: "/img/C_Chun_26.webp",
        arrows: ["/img/Kick.webp"],
      },
    ],
    throws: [
      {
        characterName: "Chun",
        comboName: "Koshuto",
        img: "/img/C_Chun_27.webp",
        arrows: [
          "/img/N.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Chun",
        comboName: "Taiji Fan",
        img: "/img/C_Chun_28.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Chun",
        comboName: "Ryuseraku",
        img: "/img/C_Chun_29.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
    ],
    common: [
      {
        characterName: "Chun",
        comboName: "Drive Reversal Hoyoku Kick",
        img: "/img/C_Chun_30.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Drive Impact Hosen Kick",
        img: "/img/C_Chun_31.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Chun",
        comboName: "Drive Parry",
        img: "/img/C_Chun_32.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Parry Drive Rush",
        left: 2,
        img: "/img/C_Chun_33.webp",
        energy: "/img/E_0,5.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Chun",
        comboName: "Cancel Drive Rush",
        img: "/img/C_Chun_34.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
