export const data = [
  {
    name: "Dee",
    zoom: 6,
    main: 2,
    img: "/test",
    imgActive: "/img/DeeA.webp",
    imgNotActive: "/img/DeeN.webp",
    describe:
      "A globally popular dance music superstar, Dee Jay is always ready to have a good time. With a burning love for music and fighting, this Jamaican sensation drives audiences wild with hot new songs and stylish moves.",
    hates: "Silence",
    likes: "Singing, dancing, hollering",
    height: "6'0",
    weight: "203 lbs",
    img1: "/img/O_Dee_1.webp",
    img2: "/img/O_Dee_2.webp",
    out1: [
      "/img/DeeF_01.webp",
      "/img/DeeF_02.webp",
      "/img/DeeF_03.webp",
      "/img/DeeF_04.webp",
      "/img/DeeF_05.webp",
      "/img/DeeF_06.webp",
      "/img/DeeF_07.webp",
      "/img/DeeF_08.webp",
      "/img/DeeF_09.webp",
    ],
    out2: [
      "/img/DeeS_01.webp",
      "/img/DeeS_02.webp",
      "/img/DeeS_03.webp",
      "/img/DeeS_04.webp",
      "/img/DeeS_05.webp",
      "/img/DeeS_06.webp",
      "/img/DeeS_07.webp",
      "/img/DeeS_08.webp",
      "/img/DeeS_09.webp",
      "/img/DeeS_10.webp",
    ],
    video: [
      {
        characterName: "Dee",
        comboName: "Air Slasher",
        video: "/img/V_Dee_1.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Jackknife Maximum",
        video: "/img/V_Dee_2.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Roll Through Feint",
        video: "/img/V_Dee_3.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Quick Rolling Sobat",
        video: "/img/V_Dee_4.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Double Rolling Sobat",
        video: "/img/V_Dee_5.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Machine Gun Uppercut",
        video: "/img/V_Dee_6.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Jus Cool",
        video: "/img/V_Dee_7.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Funky Slicer",
        video: "/img/V_Dee_8.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Waning Moon",
        video: "/img/V_Dee_9.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Maximum Strike",
        video: "/img/V_Dee_10.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Juggling Dash",
        video: "/img/V_Dee_11.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Juggling Sway",
        video: "/img/V_Dee_12.mp4",
      },
      {
        characterName: "Dee",
        comboName: "The Greatest Sobat",
        video: "/img/V_Dee_13.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Lowkey Sunrise Festival",
        video: "/img/V_Dee_14.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Marvelous Sunrise",
        video: "/img/V_Dee_15.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Headliner Sunrise",
        video: "/img/V_Dee_16.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Climactic Strike",
        video: "/img/V_Dee_17.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Encore Beat",
        video: "/img/V_Dee_18.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Weekend Pleasure",
        video: "/img/V_Dee_19.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Knee Shot",
        video: "/img/V_Dee_20.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Sunrise Heel",
        video: "/img/V_Dee_21.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Face Breaker",
        video: "/img/V_Dee_22.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Threebeat Combo",
        video: "/img/V_Dee_23.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Dee Jay Special",
        video: "/img/V_Dee_24.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Funky Dance",
        video: "/img/V_Dee_25.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Funke Dance Feint",
        video: "/img/V_Dee_26.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Party in the Air",
        video: "/img/V_Dee_27.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Speedy Maracas",
        video: "/img/V_Dee_28.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Diss Track",
        video: "/img/V_Dee_29.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Flip Throw",
        video: "/img/V_Dee_30.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Drive Impact Wild Beat",
        video: "/img/V_Dee_31.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Drive Reversal Leg Scratch",
        video: "/img/V_Dee_32.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Drive Parry Dee",
        video: "/img/V_Dee_33.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Parry Drive Rush Dee",
        video: "/img/V_Dee_34.mp4",
      },
      {
        characterName: "Dee",
        comboName: "Cancel Drive Rush Dee",
        video: "/img/V_Dee_35.mp4",
      },
    ],
    special: [
      {
        characterName: "Dee",
        comboName: "Air Slasher",
        img: "/img/C_Dee_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/L.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Jackknife Maximum",
        img: "/img/C_Dee_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/Up.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Roll Through Feint",
        img: "/img/C_Dee_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Quick Rolling Sobat",
        img: "/img/C_Dee_4.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Double Rolling Sobat",
        img: "/img/C_Dee_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Machine Gun Uppercut",
        img: "/img/C_Dee_6.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Jus Cool",
        img: "/img/C_Dee_7.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Funky Slicer",
        img: "/img/C_Dee_8.webp",
        left: 1,
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Waning Moon",
        img: "/img/C_Dee_9.webp",
        left: 1,
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Maximum Strike",
        img: "/img/C_Dee_10.webp",
        left: 1,
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Juggling Dash",
        left: 1,
        img: "/img/C_Dee_11.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Juggling Sway",
        img: "/img/C_Dee_12.webp",
        left: 2,
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
    ],
    supel: [
      {
        characterName: "Dee",
        comboName: "The Greatest Sobat",
        img: "/img/C_Dee_13.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Lowkey Sunrise Festival",
        img: "/img/C_Dee_14.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Marvelous Sunrise",
        img: "/img/C_Dee_15.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Headliner Sunrise",
        img: "/img/C_Dee_16.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Climactic Strike",
        img: "/img/C_Dee_17.webp",
        arrows: ["/img/Punch.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Encore Beat",
        img: "/img/C_Dee_18.webp",
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Weekend Pleasure",
        img: "/img/C_Dee_19.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Dee",
        comboName: "Knee Shot",
        img: "/img/C_Dee_20.webp",
        arrows: ["/img/D.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Sunrise Heel",
        img: "/img/C_Dee_21.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Face Breaker",
        img: "/img/C_Dee_22.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Threebeat Combo",
        img: "/img/C_Dee_23.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Dee Jay Special",
        img: "/img/C_Dee_24.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Funky Dance",
        img: "/img/C_Dee_25.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Funke Dance Feint",
        img: "/img/C_Dee_26.webp",
        arrows: [
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/L.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Party in the Air",
        img: "/img/C_Dee_27.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Speedy Maracas",
        img: "/img/C_Dee_28.webp",
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    throws: [
      {
        characterName: "Dee",
        comboName: "Diss Track",
        img: "/img/C_Dee_29.webp",
        arrows: [
          "/img/N.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Flip Throw",
        img: "/img/C_Dee_30.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    common: [
      {
        characterName: "Dee",
        comboName: "Drive Impact Wild Beat",
        img: "/img/C_Dee_31.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Drive Reversal Leg Scratch",
        img: "/img/C_Dee_32.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dee",
        comboName: "Drive Parry Dee",
        img: "/img/C_Dee_33.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Parry Drive Rush Dee",
        img: "/img/C_Dee_34.webp",
        energy: "/img/E_0,5.webp",
        left: 2,
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Dee",
        comboName: "Cancel Drive Rush Dee",
        img: "/img/C_Dee_35.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
