export const data = [
  {
    name: "Dhalsim",
    zoom: 2,
    main: 6,
    img: "test",
    imgActive: "/img/DhalsimA.webp",
    imgNotActive: "/img/DhalsimN.webp",
    describe:
      "A monk and yoga master from India who has served as a guide for countless suffering souls. Prefers to avoid conflict when possible, but his innate hatred of evil compels him to dispense stern justice.",
    hates: "Distractions, harming others",
    likes: "Meditating",
    height: "5'9 (can vary)",
    weight: "106 lbs (can vary)",
    img1: "/img/O_Dhalsim_1.webp",
    img2: "/img/O_Dhalsim_2.webp",
    out1: [
      "/img/DhalsimF_01.webp",
      "/img/DhalsimF_02.webp",
      "/img/DhalsimF_03.webp",
      "/img/DhalsimF_04.webp",
      "/img/DhalsimF_05.webp",
      "/img/DhalsimF_06.webp",
      "/img/DhalsimF_07.webp",
      "/img/DhalsimF_08.webp",
      "/img/DhalsimF_09.webp",
    ],
    out2: [
      "/img/DhalsimS_01.webp",
      "/img/DhalsimS_02.webp",
      "/img/DhalsimS_03.webp",
      "/img/DhalsimS_04.webp",
      "/img/DhalsimS_05.webp",
      "/img/DhalsimS_06.webp",
      "/img/DhalsimS_07.webp",
      "/img/DhalsimS_08.webp",
      "/img/DhalsimS_09.webp",
      "/img/DhalsimS_10.webp",
    ],
    video: [
      {
        characterName: "Dhalsim",
        comboName: "Yoga Fire",
        video: "/img/V_Dhalsim_1.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Arch",
        video: "/img/V_Dhalsim_2.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Flame",
        video: "/img/V_Dhalsim_3.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Blast",
        video: "/img/V_Dhalsim_4.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Comet",
        video: "/img/V_Dhalsim_5.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Float",
        video: "/img/V_Dhalsim_6.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Aerial Yoga Float",
        video: "/img/V_Dhalsim_7.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Teleport",
        video: "/img/V_Dhalsim_8.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Aerial Yoga Teleport",
        video: "/img/V_Dhalsim_9.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Inferno",
        video: "/img/V_Dhalsim_10.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Sunburst",
        video: "/img/V_Dhalsim_11.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Merciless Yoga",
        video: "/img/V_Dhalsim_12.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Uppercut",
        video: "/img/V_Dhalsim_13.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Lance",
        video: "/img/V_Dhalsim_14.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Nirvana Punch",
        video: "/img/V_Dhalsim_15.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Agile Kick",
        video: "/img/V_Dhalsim_16.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Divine Kick",
        video: "/img/V_Dhalsim_17.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Thrust Kick",
        video: "/img/V_Dhalsim_18.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Mountain",
        video: "/img/V_Dhalsim_19.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Karma Kick",
        video: "/img/V_Dhalsim_20.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Mummy",
        video: "/img/V_Dhalsim_21.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Drill Kick",
        video: "/img/V_Dhalsim_22.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Smash",
        video: "/img/V_Dhalsim_23.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Throw",
        video: "/img/V_Dhalsim_24.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Splash",
        video: "/img/V_Dhalsim_25.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Drive Impact Yoga Rise",
        video: "/img/V_Dhalsim_26.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Drive Reversal Yoga Illusion",
        video: "/img/V_Dhalsim_27.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Drive Parry",
        video: "/img/V_Dhalsim_28.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Parry Drive Rush",
        video: "/img/V_Dhalsim_29.mp4",
      },
      {
        characterName: "Dhalsim",
        comboName: "Cancel Drive Rush",
        video: "/img/V_Dhalsim_30.mp4",
      },
    ],
    special: [
      {
        characterName: "Dhalsim",
        comboName: "Yoga Fire",
        img: "/img/C_Dhalsim_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Arch",
        img: "/img/C_Dhalsim_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Flame",
        img: "/img/C_Dhalsim_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Dr.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Blast",
        img: "/img/C_Dhalsim_4.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Dr.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Comet",
        img: "/img/C_Dhalsim_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Dr.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Float",
        img: "/img/C_Dhalsim_6.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dhalsim",
        comboName: "Aerial Yoga Float",
        img: "/img/C_Dhalsim_7.webp",
        arrows: [
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Teleport",
        img: "/img/C_Dhalsim_8.webp",
        arrows: [
          "/img/R.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Dhalsim",
        comboName: "Aerial Yoga Teleport",
        img: "/img/C_Dhalsim_9.webp",
        arrows: [
          "/img/L.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    supel: [
      {
        characterName: "Dhalsim",
        comboName: "Yoga Inferno",
        img: "/img/C_Dhalsim_10.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Sunburst",
        img: "/img/C_Dhalsim_11.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dhalsim",
        comboName: "Merciless Yoga",
        img: "/img/C_Dhalsim_12.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    unique: [
      {
        img: "/img/C_Dhalsim_13.webp",
        characterName: "Dhalsim",
        comboName: "Yoga Uppercut",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Lance",
        img: "/img/C_Dhalsim_14.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Dhalsim",
        comboName: "Nirvana Punch",
        img: "/img/C_Dhalsim_15.webp",
        arrows: ["/img/Dl.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Dhalsim",
        comboName: "Agile Kick",
        img: "/img/C_Dhalsim_16.webp",
        arrows: ["/img/Dl.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dhalsim",
        comboName: "Divine Kick",
        img: "/img/C_Dhalsim_17.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dhalsim",
        comboName: "Thrust Kick",
        img: "/img/C_Dhalsim_18.webp",
        arrows: ["/img/Dl.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Mountain",
        img: "/img/C_Dhalsim_19.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dhalsim",
        comboName: "Karma Kick",
        img: "/img/C_Dhalsim_20.webp",
        arrows: ["/img/Dl.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Mummy",
        img: "/img/C_Dhalsim_21.webp",
        arrows: ["/img/D.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Dhalsim",
        comboName: "Drill Kick",
        img: "/img/C_Dhalsim_22.webp",
        arrows: ["/img/D.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
    ],
    throws: [
      {
        characterName: "Dhalsim",
        comboName: "Yoga Smash",
        img: "/img/C_Dhalsim_23.webp",
        arrows: [
          "/img/N.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Throw",
        img: "/img/C_Dhalsim_24.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dhalsim",
        comboName: "Yoga Splash",
        img: "/img/C_Dhalsim_25.webp",
        arrows: [
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    common: [
      {
        characterName: "Dhalsim",
        comboName: "Drive Impact Yoga Rise",
        img: "/img/C_Dhalsim_26.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dhalsim",
        comboName: "Drive Reversal Yoga Illusion",
        img: "/img/C_Dhalsim_27.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Dhalsim",
        comboName: "Drive Parry",
        img: "/img/C_Dhalsim_28.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Dhalsim",
        comboName: "Parry Drive Rush",
        img: "/img/C_Dhalsim_29.webp",
        left: 2,
        energy: "/img/E_0,5.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Dhalsim",
        comboName: "Cancel Drive Rush",
        img: "/img/C_Dhalsim_30.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
