export const data = [
  {
    name: "Guile",
    imgActive: "/img/GuileA.webp",
    img: "test",
    imgNotActive: "/img/GuileN.webp",
    describe:
      "A US Air Force pilot who fights for his country, Guile succeeded in dismantling Shadaloo and avenging his friend Charlie. He enjoys living the family man life, but new battlefields await him.",
    hates: "Secretive people, layabouts",
    likes: "Watching sports, dog walking",
    height: "6'0",
    weight: "218 lbs",
    img1: "/img/O_Guile_1.webp",
    img2: "/img/O_Guile_2.webp",
    out1: [
      "/img/GuileF_01.webp",
      "/img/GuileF_02.webp",
      "/img/GuileF_03.webp",
      "/img/GuileF_04.webp",
      "/img/GuileF_05.webp",
      "/img/GuileF_06.webp",
      "/img/GuileF_07.webp",
      "/img/GuileF_08.webp",
      "/img/GuileF_09.webp",
    ],
    out2: [
      "/img/GuileS_01.webp",
      "/img/GuileS_02.webp",
      "/img/GuileS_03.webp",
      "/img/GuileS_04.webp",
      "/img/GuileS_05.webp",
      "/img/GuileS_06.webp",
      "/img/GuileS_07.webp",
      "/img/GuileS_08.webp",
      "/img/GuileS_09.webp",
      "/img/GuileS_10.webp",
    ],
    video: [
      {
        characterName: "Guile",
        comboName: "Sonic Boom",
        video: "/img/V_Guile_1.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Somersault Kick",
        video: "/img/V_Guile_2.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Sonic Blame",
        video: "/img/V_Guile_3.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Sonic Cross",
        video: "/img/V_Guile_4.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Sonic Break",
        video: "/img/V_Guile_5.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Sonic Braek",
        video: "/img/V_Guile_6.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Sonic Hurricane",
        video: "/img/V_Guile_7.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Solid Puncher",
        video: "/img/V_Guile_8.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Crossfire Somersault",
        video: "/img/V_Guile_9.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Full Bullet Magnum",
        video: "/img/V_Guile_10.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Burning Straight",
        video: "/img/V_Guile_11.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Spinning Back Knuckle",
        video: "/img/V_Guile_12.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Knee Bazooka",
        video: "/img/V_Guile_13.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Rolling Sobat",
        video: "/img/V_Guile_14.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Reverse Spin Kick",
        video: "/img/V_Guile_15.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Guile High Kick",
        video: "/img/V_Guile_16.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Recoil Cannon",
        video: "/img/V_Guile_17.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Double Shot",
        video: "/img/V_Guile_18.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Drake Fang",
        video: "/img/V_Guile_19.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Phantom Cutter",
        video: "/img/V_Guile_20.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Dragon Suplex",
        video: "/img/V_Guile_21.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Judo Throw",
        video: "/img/V_Guile_22.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Flying Mare",
        video: "/img/V_Guile_23.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Flying Buster Drop",
        video: "/img/V_Guile_24.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Drive Impact Blitz Combination",
        video: "/img/V_Guile_25.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Drive Reversal Strike Eagle",
        video: "/img/V_Guile_26.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Drive Parry",
        video: "/img/V_Guile_27.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Pappy Drive Rush",
        video: "/img/V_Guile_28.mp4",
      },
      {
        characterName: "Guile",
        comboName: "Cancel Drive Rush",
        video: "/img/V_Guile_29.mp4",
      },
    ],
    special: [
      {
        characterName: "Guile",
        comboName: "Sonic Boom",
        img: "/img/C_Guile_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/L.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Guile",
        comboName: "Somersault Kick",
        img: "/img/C_Guile_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Up.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Guile",
        comboName: "Sonic Blame",
        img: "/img/C_Guile_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Guile",
        comboName: "Sonic Cross",
        img: "/img/C_Guile_4.webp",
        left: 2,
        energy: "/img/E_2.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Guile",
        comboName: "Sonic Break",
        img: "/img/C_Guile_5.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Guile",
        comboName: "Sonic Braek",
        left: 2,
        img: "/img/C_Guile_6.webp",
        arrows: ["/img/Punch.webp"],
      },
    ],
    supel: [
      {
        characterName: "Guile",
        comboName: "Sonic Hurricane",
        img: "/img/C_Guile_7.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/L.webp",
          "/img/R.webp",
          "/img/L.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Guile",
        comboName: "Solid Puncher",
        img: "/img/C_Guile_8.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Guile",
        comboName: "Crossfire Somersault",
        img: "/img/C_Guile_9.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/L.webp",
          "/img/R.webp",
          "/img/L.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Guile",
        comboName: "Full Bullet Magnum",
        img: "/img/C_Guile_10.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Guile",
        comboName: "Burning Straight",
        img: "/img/C_Guile_11.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Guile",
        comboName: "Spinning Back Knuckle",
        img: "/img/C_Guile_12.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Guile",
        comboName: "Knee Bazooka",
        img: "/img/C_Guile_13.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Guile",
        comboName: "Rolling Sobat",
        img: "/img/C_Guile_14.webp",
        arrows: [
          "/img/L.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Guile",
        comboName: "Reverse Spin Kick",
        img: "/img/C_Guile_15.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Guile",
        comboName: "Guile High Kick",
        img: "/img/C_Guile_16.webp",
        arrows: ["/img/Dr.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Guile",
        comboName: "Recoil Cannon",
        img: "/img/C_Guile_17.webp",
        arrows: [
          "/img/Punch.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Guile",
        comboName: "Double Shot",
        img: "/img/C_Guile_18.webp",
        arrows: [
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/D.webp",
          "/img/Plus.webp",
        ],
      },
      {
        characterName: "Guile",
        comboName: "Drake Fang",
        img: "/img/C_Guile_19.webp",
        arrows: [
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Guile",
        comboName: "Phantom Cutter",
        img: "/img/C_Guile_20.webp",
        arrows: [
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    throws: [
      {
        characterName: "Guile",
        comboName: "Dragon Suplex",
        img: "/img/C_Guile_21.webp",
        arrows: [
          "/img/N.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Guile",
        comboName: "Judo Throw",
        img: "/img/C_Guile_22.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Guile",
        comboName: "Flying Mare",
        img: "/img/C_Guile_23.webp",
        arrows: [
          "/img/N.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Guile",
        comboName: "Flying Buster Drop",
        img: "/img/C_Guile_24.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    common: [
      {
        characterName: "Guile",
        comboName: "Drive Impact Blitz Combination",
        img: "/img/C_Guile_25.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Guile",
        comboName: "Drive Reversal Strike Eagle",
        img: "/img/C_Guile_26.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Guile",
        comboName: "Drive Parry",
        img: "/img/C_Guile_27.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Guile",
        comboName: "Pappy Drive Rush",
        img: "/img/C_Guile_28.webp",
        left: 2,
        energy: "/img/E_0,5.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Guile",
        comboName: "Cancel Drive Rush",
        img: "/img/C_Guile_29.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
