export const data = [
  {
    name: "Honda",
    zoom: 1,
    img: "test",
    main: 7,
    imgActive: "/img/HondaA.webp",
    imgNotActive: "/img/HondaN.webp",
    describe:
      "A sumo wrestler looking to bring the sport worldwide, E. Honda has the skills of a yokozuna, but his constant globetrotting has prevented his promotion. Also an expert chef renowned for mouthwatering chanko stew.",
    hates: "Indecisiveness",
    likes: "Baths",
    height: "6'1",
    weight: "302 lbs",
    img1: "/img/O_Honda_1.webp",
    img2: "/img/O_Honda_2.webp",
    out1: [
      "/img/HondaF_01.webp",
      "/img/HondaF_02.webp",
      "/img/HondaF_03.webp",
      "/img/HondaF_04.webp",
      "/img/HondaF_05.webp",
      "/img/HondaF_06.webp",
      "/img/HondaF_07.webp",
      "/img/HondaF_08.webp",
      "/img/HondaF_09.webp",
    ],
    out2: [
      "/img/HondaS_01.webp",
      "/img/HondaS_02.webp",
      "/img/HondaS_03.webp",
      "/img/HondaS_04.webp",
      "/img/HondaS_05.webp",
      "/img/HondaS_06.webp",
      "/img/HondaS_07.webp",
      "/img/HondaS_08.webp",
      "/img/HondaS_09.webp",
      "/img/HondaS_10.webp",
    ],
    video: [
      {
        characterName: "Honda",
        comboName: "Hundred Hand Slap",
        video: "/img/V_Honda_1.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Sumo Headbutt",
        video: "/img/V_Honda_2.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Sumo Smash",
        video: "/img/V_Honda_3.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Oicho Throw",
        video: "/img/V_Honda_4.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Sumo Dash",
        video: "/img/V_Honda_5.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Teppo Triple Slap",
        video: "/img/V_Honda_6.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Taiho Cannon Lift",
        video: "/img/V_Honda_7.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Neko Damashi",
        video: "/img/V_Honda_8.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Sumo Spirit",
        video: "/img/V_Honda_9.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Show of Force",
        video: "/img/V_Honda_10.mp4",
      },
      {
        characterName: "Honda",
        comboName: "ultimate Killer Head",
        video: "/img/V_Honda_11.mp4",
      },
      {
        characterName: "Honda",
        comboName: "The Final Bout",
        video: "/img/V_Honda_12.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Harai Kick",
        video: "/img/V_Honda_13.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Power Stomp",
        video: "/img/V_Honda_14.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Flying Sumo Press",
        video: "/img/V_Honda_15.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Double Slaps",
        video: "/img/V_Honda_16.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Toko Shizume",
        video: "/img/V_Honda_17.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Saba Ori",
        video: "/img/V_Honda_18.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Tawara Throw",
        video: "/img/V_Honda_19.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Drive Impact Sumo Cruch",
        video: "/img/V_Honda_20.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Drive Reversal Raiden-Ho",
        video: "/img/V_Honda_21.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Drive Parry Honda",
        video: "/img/V_Honda_22.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Parry Drive Rush Honda",
        video: "/img/V_Honda_23.mp4",
      },
      {
        characterName: "Honda",
        comboName: "Cancel Drive Rush Honda",
        video: "/img/V_Honda_24.mp4",
      },
    ],
    special: [
      {
        characterName: "Honda",
        comboName: "Hundred Hand Slap",
        img: "/img/C_Honda_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Honda",
        comboName: "Sumo Headbutt",
        img: "/img/C_Honda_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/L.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Honda",
        comboName: "Sumo Smash",
        img: "/img/C_Honda_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Up.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Honda",
        comboName: "Oicho Throw",
        img: "/img/C_Honda_4.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Dr.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Honda",
        comboName: "Sumo Dash",
        img: "/img/C_Honda_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Honda",
        comboName: "Teppo Triple Slap",
        img: "/img/C_Honda_6.webp",
        left: 1,
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Honda",
        comboName: "Taiho Cannon Lift",
        img: "/img/C_Honda_7.webp",
        left: 2,
        arrows: ["/img/D.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Honda",
        comboName: "Neko Damashi",
        img: "/img/C_Honda_8.webp",
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Honda",
        comboName: "Sumo Spirit",
        img: "/img/C_Honda_9.webp",
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    supel: [
      {
        characterName: "Honda",
        comboName: "Show of Force",
        img: "/img/C_Honda_10.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Honda",
        comboName: "ultimate Killer Head",
        img: "/img/C_Honda_11.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/L.webp",
          "/img/R.webp",
          "/img/L.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Honda",
        comboName: "The Final Bout",
        img: "/img/C_Honda_12.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Honda",
        comboName: "Harai Kick",
        img: "/img/C_Honda_13.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Honda",
        comboName: "Power Stomp",
        img: "/img/C_Honda_14.webp",
        arrows: ["/img/Dr.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Honda",
        comboName: "Flying Sumo Press",
        img: "/img/C_Honda_15.webp",
        arrows: ["/img/D.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Honda",
        comboName: "Double Slaps",
        img: "/img/C_Honda_16.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Honda",
        comboName: "Toko Shizume",
        img: "/img/C_Honda_17.webp",
        arrows: [
          "/img/Punch.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    throws: [
      {
        characterName: "Honda",
        comboName: "Saba Ori",
        img: "/img/C_Honda_18.webp",
        arrows: [
          "/img/N.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Honda",
        comboName: "Tawara Throw",
        img: "/img/C_Honda_19.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    common: [
      {
        characterName: "Honda",
        comboName: "Drive Impact Sumo Cruch",
        img: "/img/C_Honda_20.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Honda",
        comboName: "Drive Reversal Raiden-Ho",
        img: "/img/C_Honda_21.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Honda",
        comboName: "Drive Parry Honda",
        img: "/img/C_Honda_22.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Honda",
        comboName: "Parry Drive Rush Honda",
        img: "/img/C_Honda_23.webp",
        left: 2,
        energy: "/img/E_0,5.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Honda",
        comboName: "Cancel Drive Rush Honda",
        img: "/img/C_Honda_24.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
