export const data = [
  {
    name: "Jamie",
    zoom: 2,
    img: "test",
    main: 5,
    imgActive: "/img/JamieA.webp",
    imgNotActive: "/img/JamieN.webp",
    describe:
      "This self-styled Chinatown peacekeeper aspires to the example set by Yun and Yang, the Twin Dragons. An expert dancer, Jamie places justice and friendship above all else, defending his town with martial skill.",
    hates: "Getting lectured, arrogance",
    likes: "Yun, Yang, dancing, his grandmother",
    height: "5'9",
    weight: "170 lbs",
    img1: "/img/O_Jamie_1.webp",
    img2: "/img/O_Jamie_2.webp",
    out1: [
      "/img/JamieF_01.webp",
      "/img/JamieF_02.webp",
      "/img/JamieF_03.webp",
      "/img/JamieF_04.webp",
      "/img/JamieF_05.webp",
      "/img/JamieF_06.webp",
      "/img/JamieF_07.webp",
      "/img/JamieF_08.webp",
      "/img/JamieF_09.webp",
    ],
    out2: [
      "/img/JamieS_01.webp",
      "/img/JamieS_02.webp",
      "/img/JamieS_03.webp",
      "/img/JamieS_04.webp",
      "/img/JamieS_05.webp",
      "/img/JamieS_06.webp",
      "/img/JamieS_07.webp",
      "/img/JamieS_08.webp",
      "/img/JamieS_09.webp",
      "/img/JamieS_10.webp",
    ],
    video: [
      {
        characterName: "Jamie",
        comboName: "The Devil Inside",
        video: "/img/V_Jamie_1.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Freeflow Strike",
        video: "/img/V_Jamie_2.mp4",
      },
      {
        video: "/img/V_Jamie_3.mp4",
        characterName: "Jamie",
        comboName: "Freeflow Kicks",
      },
      {
        characterName: "Jamie",
        comboName: "Swagger Step",
        video: "/img/V_Jamie_4.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Arrow Kick",
        video: "/img/V_Jamie_5.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Luminous Drive Kick",
        video: "/img/V_Jamie_6.mp4",
      },
      {
        video: "/img/V_Jamie_7.mp4",
        characterName: "Jamie",
        comboName: "Bakkai",
      },
      {
        characterName: "Jamie",
        comboName: "Tenshin",
        video: "/img/V_Jamie_8.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Swagger Hermit Punch",
        video: "/img/V_Jamie_9.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Breakin",
        video: "/img/V_Jamie_10.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "The Devils Song",
        video: "/img/V_Jamie_11.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Getsuga Saiho",
        video: "/img/V_Jamie_12.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Tensei Kick",
        video: "/img/V_Jamie_13.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Phantom Sway",
        video: "/img/V_Jamie_14.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Falling Star Kick",
        video: "/img/V_Jamie_15.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Hermits Elbow",
        video: "/img/V_Jamie_16.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Senei Kick",
        video: "/img/V_Jamie_17.mp4",
      },
      {
        video: "/img/V_Jamie_18.mp4",
        characterName: "Jamie",
        comboName: "Bitter Strikes",
      },
      {
        characterName: "Jamie",
        comboName: "Full Moon Kick",
        video: "/img/V_Jamie_19.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Intoxicated Assault",
        video: "/img/V_Jamie_20.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Ransui Haze",
        video: "/img/V_Jamie_21.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Back Shaver",
        video: "/img/V_Jamie_22.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Wheel Punch",
        video: "/img/V_Jamie_23.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Drive Impact Vainglory Strike",
        video: "/img/V_Jamie_24.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Drive Reversal Leg Sweep",
        video: "/img/V_Jamie_25.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Drive Parry",
        video: "/img/V_Jamie_26.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Parry Drive Rush",
        video: "/img/V_Jamie_27.mp4",
      },
      {
        characterName: "Jamie",
        comboName: "Cancel Drive Rush",
        video: "/img/V_Jamie_28.mp4",
      },
    ],
    special: [
      {
        characterName: "Jamie",
        comboName: "The Devil Inside",
        img: "/img/C_Jamie_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Freeflow Strike",
        img: "/img/C_Jamie_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Freeflow Kicks",
        img: "/img/C_Jamie_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/R.webp",
          "/img/Kick.webp",
          "/img/Plus.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Swagger Step",
        img: "/img/C_Jamie_4.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Arrow Kick",
        img: "/img/C_Jamie_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Luminous Drive Kick",
        img: "/img/C_Jamie_6.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Bakkai",
        img: "/img/C_Jamie_7.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Tenshin",
        img: "/img/C_Jamie_8.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Dr.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Swagger Hermit Punch",
        img: "/img/C_Jamie_9.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    supel: [
      {
        characterName: "Jamie",
        comboName: "Breakin",
        img: "/img/C_Jamie_10.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "The Devils Song",
        img: "/img/C_Jamie_11.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Getsuga Saiho",
        img: "/img/C_Jamie_12.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Jamie",
        comboName: "Tensei Kick",
        img: "/img/C_Jamie_13.webp",
        arrows: [
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Phantom Sway",
        img: "/img/C_Jamie_14.webp",
        arrows: [
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Falling Star Kick",
        img: "/img/C_Jamie_15.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        img: "/img/C_Jamie_16.webp",
        characterName: "Jamie",
        comboName: "Hermits Elbow",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Jamie",
        comboName: "Senei Kick",
        img: "/img/C_Jamie_17.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Jamie",
        comboName: "Bitter Strikes",
        img: "/img/C_Jamie_18.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Jamie",
        comboName: "Full Moon Kick",
        img: "/img/C_Jamie_19.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Intoxicated Assault",
        img: "/img/C_Jamie_20.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Ransui Haze",
        img: "/img/C_Jamie_21.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    throws: [
      {
        characterName: "Jamie",
        comboName: "Back Shaver",
        img: "/img/C_Jamie_22.webp",
        arrows: [
          "/img/N.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Wheel Punch",
        img: "/img/C_Jamie_23.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    common: [
      {
        characterName: "Jamie",
        comboName: "Drive Impact Vainglory Strike",
        img: "/img/C_Jamie_24.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Jamie",
        comboName: "Drive Reversal Leg Sweep",
        img: "/img/C_Jamie_25.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Jamie",
        comboName: "Drive Parry",
        img: "/img/C_Jamie_26.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Jamie",
        comboName: "Parry Drive Rush",
        img: "/img/C_Jamie_27.webp",
        left: 2,
        energy: "/img/E_0,5.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Jamie",
        comboName: "Cancel Drive Rush",
        img: "/img/C_Jamie_28.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
