export const data = [
  {
    name: "JP",
    img: "test",
    // zoom: 4,
    // main: 4,
    imgActive: "/img/JPA.webp",
    imgNotActive: "/img/JPN.webp",
    describe:
      "Head of an international NGO responsible for many successful investment projects, and the man behind Nayshall's present prosperity. Has a beloved cat named Cybele.",
    hates: "Stains on his clothes, sleep",
    likes: "Chess puzzles, cleaning, local cuisines",
    height: "6'3",
    weight: "214 lbs",
    img1: "/img/O_JP_1.webp",
    img2: "/img/O_JP_2.webp",
    out1: [
      "/img/JPF_01.webp",
      "/img/JPF_02.webp",
      "/img/JPF_03.webp",
      "/img/JPF_04.webp",
      "/img/JPF_05.webp",
      "/img/JPF_06.webp",
      "/img/JPF_07.webp",
      "/img/JPF_08.webp",
      "/img/JPF_09.webp",
    ],
    out2: [
      "/img/JPS_01.webp",
      "/img/JPS_02.webp",
      "/img/JPS_03.webp",
      "/img/JPS_04.webp",
      "/img/JPS_05.webp",
      "/img/JPS_06.webp",
      "/img/JPS_07.webp",
      "/img/JPS_08.webp",
      "/img/JPS_09.webp",
      "/img/JPS_10.webp",
    ],
    video: [
      {
        characterName: "JP",
        comboName: "Triglav",
        video: "/img/V_JP_1.mp4",
      },
      {
        characterName: "JP",
        comboName: "Stribog",
        video: "/img/V_JP_2.mp4",
      },
      {
        characterName: "JP",
        comboName: "Departure",
        video: "/img/V_JP_3.mp4",
      },
      {
        characterName: "JP",
        comboName: "Departure Windows",
        video: "/img/V_JP_4.mp4",
      },
      {
        characterName: "JP",
        comboName: "Departure Shadow",
        video: "/img/V_JP_5.mp4",
      },
      {
        characterName: "JP",
        comboName: "Amnesia",
        video: "/img/V_JP_6.mp4",
      },
      {
        characterName: "JP",
        comboName: "Torbalan",
        video: "/img/V_JP_7.mp4",
      },
      {
        characterName: "JP",
        comboName: "Embrace",
        video: "/img/V_JP_8.mp4",
      },
      {
        characterName: "JP",
        comboName: "Chornobog",
        video: "/img/V_JP_9.mp4",
      },
      {
        characterName: "JP",
        comboName: "Lovushka",
        video: "/img/V_JP_10.mp4",
      },
      {
        characterName: "JP",
        comboName: "Interdiction",
        video: "/img/V_JP_11.mp4",
      },
      {
        characterName: "JP",
        comboName: "Guillotinna",
        video: "/img/V_JP_12.mp4",
      },
      {
        characterName: "JP",
        comboName: "Malice",
        video: "/img/V_JP_13.mp4",
      },
      {
        characterName: "JP",
        comboName: "Bylina",
        video: "/img/V_JP_14.mp4",
      },
      {
        characterName: "JP",
        comboName: "Grom Strelka",
        video: "/img/V_JP_15.mp4",
      },
      {
        characterName: "JP",
        comboName: "Zilant",
        video: "/img/V_JP_16.mp4",
      },
      {
        characterName: "JP",
        comboName: "Zilant Mid",
        video: "/img/V_JP_17.mp4",
      },
      {
        characterName: "JP",
        comboName: "Zilant Low",
        video: "/img/V_JP_18.mp4",
      },
      {
        characterName: "JP",
        comboName: "Ravina",
        video: "/img/V_JP_19.mp4",
      },
      {
        characterName: "JP",
        comboName: "Uragan",
        video: "/img/V_JP_20.mp4",
      },
      {
        characterName: "JP",
        comboName: "Tornado",
        video: "/img/V_JP_21.mp4",
      },
      {
        characterName: "JP",
        comboName: "Drive Impact Espada",
        video: "/img/V_JP_22.mp4",
      },
      {
        characterName: "JP",
        comboName: "Drive Impact Exilio",
        video: "/img/V_JP_23.mp4",
      },
      {
        characterName: "JP",
        comboName: "Drive Parry JP",
        video: "/img/V_JP_24.mp4",
      },
      {
        characterName: "JP",
        comboName: "Parry Drive Rush JP",
        video: "/img/V_JP_25.mp4",
      },
      {
        characterName: "JP",
        comboName: "Cancel Drive JP",
        video: "/img/V_JP_26.mp4",
      },
    ],
    special: [
      {
        characterName: "JP",
        comboName: "Triglav",
        img: "/img/C_JP_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "JP",
        comboName: "Stribog",
        img: "/img/C_JP_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "JP",
        comboName: "Departure",
        img: "/img/C_JP_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "JP",
        comboName: "Departure Windows",
        img: "/img/C_JP_4.webp",
        left: 1,
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "JP",
        comboName: "Departure Shadow",
        img: "/img/C_JP_5.webp",
        left: 2,
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "JP",
        comboName: "Amnesia",
        img: "/img/C_JP_6.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "JP",
        comboName: "Torbalan",
        img: "/img/C_JP_7.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "JP",
        comboName: "Embrace",
        img: "/img/C_JP_8.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    supel: [
      {
        characterName: "JP",
        comboName: "Chornobog",
        img: "/img/C_JP_9.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "JP",
        comboName: "Lovushka",
        img: "/img/C_JP_10.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "JP",
        comboName: "Interdiction",
        img: "/img/C_JP_11.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "JP",
        comboName: "Guillotinna",
        img: "/img/C_JP_12.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "JP",
        comboName: "Malice",
        img: "/img/C_JP_13.webp",
        arrows: ["/img/Dr.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "JP",
        comboName: "Bylina",
        img: "/img/C_JP_14.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "JP",
        comboName: "Grom Strelka",
        img: "/img/C_JP_15.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "JP",
        comboName: "Zilant",
        img: "/img/C_JP_16.webp",
        arrows: ["/img/Kick.webp", "/img/Punch.webp"],
      },
      {
        characterName: "JP",
        comboName: "Zilant Mid",
        img: "/img/C_JP_17.webp",
        arrows: ["/img/Kick.webp", "/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "JP",
        comboName: "Zilant Low",
        img: "/img/C_JP_18.webp",
        arrows: ["/img/Kick.webp", "/img/Punch.webp", "/img/Kick.webp"],
      },
    ],
    throws: [
      {
        characterName: "JP",
        comboName: "Ravina",
        img: "/img/C_JP_19.webp",
        arrows: [
          "/img/N.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "JP",
        comboName: "Uragan",
        img: "/img/C_JP_20.webp",
        arrows: ["/img/L.webp", "/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "JP",
        comboName: "Tornado",
        img: "/img/C_JP_21.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
    ],
    common: [
      {
        characterName: "JP",
        comboName: "Drive Impact Espada",
        img: "/img/C_JP_22.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "JP",
        comboName: "Drive Impact Exilio",
        img: "/img/C_JP_23.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "JP",
        comboName: "Drive Parry JP",
        img: "/img/C_JP_24.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        img: "/img/C_JP_25.webp",
        energy: "/img/E_0,5.webp",
        left: 2,
        arrows: ["/img/R.webp", "/img/R.webp"],
        characterName: "JP",
        comboName: "Parry Drive Rush JP",
      },
      {
        characterName: "JP",
        comboName: "Cancel Drive JP",
        img: "/img/C_JP_26.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
