export const data = [
  {
    name: "Juri",
    img: "test",
    zoom: 7,
    main: 8,
    imgActive: "/img/JuriA.webp",
    imgNotActive: "/img/JuriN.webp",
    describe:
      "This sadistic thrillseeker enjoys the strife and suffering of others, taking immense joy in obliterating her foes. Without revenge against M. Bison as a motivator, she whiles away her time in a gloomy haze.",
    hates: "Buzzkills, rules",
    likes: "Motorcycles, spiders",
    height: "5'5",
    weight: "126 lbs",
    img1: "/img/O_Juri_1.webp",
    img2: "/img/O_Juri_2.webp",
    out1: [
      "/img/JuriF_01.webp",
      "/img/JuriF_02.webp",
      "/img/JuriF_03.webp",
      "/img/JuriF_04.webp",
      "/img/JuriF_05.webp",
      "/img/JuriF_06.webp",
      "/img/JuriF_07.webp",
      "/img/JuriF_08.webp",
      "/img/JuriF_09.webp",
    ],
    out2: [
      "/img/JuriS_01.webp",
      "/img/JuriS_02.webp",
      "/img/JuriS_03.webp",
      "/img/JuriS_04.webp",
      "/img/JuriS_05.webp",
      "/img/JuriS_06.webp",
      "/img/JuriS_07.webp",
      "/img/JuriS_08.webp",
      "/img/JuriS_09.webp",
      "/img/JuriS_10.webp",
    ],
    video: [
      {
        characterName: "Juri",
        comboName: "Fuhajin",
        video: "/img/V_Juri_1.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Saihasho",
        video: "/img/V_Juri_2.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Ankensatsu",
        video: "/img/V_Juri_3.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Go Ohsatsu",
        video: "/img/V_Juri_4.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Tensenrin",
        video: "/img/V_Juri_5.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Shiku-sen",
        video: "/img/V_Juri_6.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Shiren-sen",
        video: "/img/V_Juri_7.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Sakkai Fuhazan",
        video: "/img/V_Juri_8.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Feng Shui Engine",
        video: "/img/V_Juri_9.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Kaisen Dankai Raku",
        video: "/img/V_Juri_10.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Kyisesho",
        video: "/img/V_Juri_11.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Senkai Kick",
        video: "/img/V_Juri_12.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Ranko Kick",
        video: "/img/V_Juri_13.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Korenzan",
        video: "/img/V_Juri_14.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Death Crest",
        video: "/img/V_Juri_15.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Spider Fang Throw",
        video: "/img/V_Juri_16.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Shadow Kick Throw",
        video: "/img/V_Juri_17.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Zanka-sen",
        video: "/img/V_Juri_18.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Drive Impact Sekkan Kick",
        video: "/img/V_Juri_19.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Drive Reversal Kaita Raid",
        video: "/img/V_Juri_20.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Drive Parry",
        video: "/img/V_Juri_21.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Parry Drive Rush",
        video: "/img/V_Juri_22.mp4",
      },
      {
        characterName: "Juri",
        comboName: "Cancel Drive Rush",
        video: "/img/V_Juri_23.mp4",
      },
    ],
    special: [
      {
        characterName: "Juri",
        comboName: "Fuhajin",
        img: "/img/C_Juri_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Juri",
        comboName: "Saihasho",
        img: "/img/C_Juri_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Juri",
        comboName: "Ankensatsu",
        img: "/img/C_Juri_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Juri",
        comboName: "Go Ohsatsu",
        img: "/img/C_Juri_4.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Juri",
        comboName: "Tensenrin",
        img: "/img/C_Juri_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Juri",
        comboName: "Shiku-sen",
        img: "/img/C_Juri_6.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Juri",
        comboName: "Shiren-sen",
        left: 2,
        img: "/img/C_Juri_7.webp",
        arrows: ["/img/Kick.webp"],
      },
    ],
    supel: [
      {
        characterName: "Juri",
        comboName: "Sakkai Fuhazan",
        img: "/img/C_Juri_8.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Juri",
        comboName: "Feng Shui Engine",
        img: "/img/C_Juri_9.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Juri",
        comboName: "Kaisen Dankai Raku",
        img: "/img/C_Juri_10.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Juri",
        comboName: "Kyisesho",
        img: "/img/C_Juri_11.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Juri",
        comboName: "Senkai Kick",
        img: "/img/C_Juri_12.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Juri",
        comboName: "Ranko Kick",
        img: "/img/C_Juri_13.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Juri",
        comboName: "Korenzan",
        img: "/img/C_Juri_14.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Juri",
        comboName: "Death Crest",
        img: "/img/C_Juri_15.webp",
        arrows: [
          "/img/Punch.webp",
          "/img/L.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    throws: [
      {
        characterName: "Juri",
        comboName: "Spider Fang Throw",
        img: "/img/C_Juri_16.webp",
        arrows: [
          "/img/N.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Juri",
        comboName: "Shadow Kick Throw",
        img: "/img/C_Juri_17.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Juri",
        comboName: "Zanka-sen",
        img: "/img/C_Juri_18.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
    ],
    common: [
      {
        characterName: "Juri",
        comboName: "Drive Impact Sekkan Kick",
        img: "/img/C_Juri_19.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Juri",
        comboName: "Drive Reversal Kaita Raid",
        img: "/img/C_Juri_20.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Juri",
        comboName: "Drive Parry",
        img: "/img/C_Juri_21.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Juri",
        comboName: "Parry Drive Rush",
        img: "/img/C_Juri_22.webp",
        left: 2,
        energy: "/img/E_0,5.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Juri",
        comboName: "Cancel Drive Rush",
        img: "/img/C_Juri_23.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
