export const data = [
  {
    name: "Ken",
    zoom: 3,
    img: "test",
    main: 6,
    imgActive: "/img/KenA.webp",
    imgNotActive: "/img/KenN.webp",
    describe:
      "Former US National Fighting Champ, and ex-VP of the Masters Foundation. Accusations of orchestrating a criminal plot have forced Ken to abandon his family and business and go into hiding.",
    hates: "Pointless meetings",
    likes: "Family",
    height: "5'9",
    weight: "183 lbs",
    img1: "/img/O_Ken_1.webp",
    img2: "/img/O_Ken_2.webp",
    out1: [
      "/img/KenF_01.webp",
      "/img/KenF_02.webp",
      "/img/KenF_03.webp",
      "/img/KenF_04.webp",
      "/img/KenF_05.webp",
      "/img/KenF_06.webp",
      "/img/KenF_07.webp",
      "/img/KenF_08.webp",
      "/img/KenF_09.webp",
    ],
    out2: [
      "/img/KenS_01.webp",
      "/img/KenS_02.webp",
      "/img/KenS_03.webp",
      "/img/KenS_04.webp",
      "/img/KenS_05.webp",
      "/img/KenS_06.webp",
      "/img/KenS_07.webp",
      "/img/KenS_08.webp",
      "/img/KenS_09.webp",
      "/img/KenS_10.webp",
    ],
    video: [
      {
        characterName: "Ken",
        comboName: "Hadoken",
        video: "/img/V_Ken_1.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Shoryuken",
        video: "/img/V_Ken_2.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Tatsumaki Senpu",
        video: "/img/V_Ken_3.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Aerial Tatsumaki Senpu",
        video: "/img/V_Ken_4.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Dragonlash Kick",
        video: "/img/V_Ken_5.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Jinrai Kick",
        video: "/img/V_Ken_6.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Kazekama Shin Kick",
        video: "/img/V_Ken_7.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Gorai Axe Kick",
        video: "/img/V_Ken_8.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Senka Snap Kick",
        video: "/img/V_Ken_9.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Kasai Thrust Kick",
        video: "/img/V_Ken_10.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Dragonlash Flame",
        video: "/img/V_Ken_11.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Shippu Jinrai",
        video: "/img/V_Ken_12.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Shinryu Reppa",
        video: "/img/V_Ken_13.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Quick Dash",
        video: "/img/V_Ken_14.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Emergency Stop",
        video: "/img/V_Ken_15.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Thunder Kick",
        video: "/img/V_Ken_16.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Forward Step Kick",
        video: "/img/V_Ken_17.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Chin Buster",
        video: "/img/V_Ken_18.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Triple Flash Kicks",
        video: "/img/V_Ken_19.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Knee Strikes",
        video: "/img/V_Ken_20.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Hell Wheel",
        video: "/img/V_Ken_21.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Drive Impact Flame Strike",
        video: "/img/V_Ken_22.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Drive Reversal Lightning Crack",
        video: "/img/V_Ken_23.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Drive Parry",
        video: "/img/V_Ken_24.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Parry Drive Rush",
        video: "/img/V_Ken_25.mp4",
      },
      {
        characterName: "Ken",
        comboName: "Cancel Drive Rush",
        video: "/img/V_Ken_26.mp4",
      },
    ],
    special: [
      {
        characterName: "Ken",
        comboName: "Hadoken",
        img: "/img/C_Ken_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Ken",
        comboName: "Shoryuken",
        img: "/img/C_Ken_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Ken",
        comboName: "Tatsumaki Senpu",
        img: "/img/C_Ken_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Ken",
        comboName: "Aerial Tatsumaki Senpu",
        img: "/img/C_Ken_4.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Ken",
        comboName: "Dragonlash Kick",
        img: "/img/C_Ken_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Ken",
        comboName: "Jinrai Kick",
        img: "/img/C_Ken_6.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Ken",
        comboName: "Kazekama Shin Kick",
        left: 1,
        img: "/img/C_Ken_7.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Ken",
        comboName: "Gorai Axe Kick",
        left: 1,
        img: "/img/C_Ken_8.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Ken",
        comboName: "Senka Snap Kick",
        left: 2,
        img: "/img/C_Ken_9.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Ken",
        comboName: "Kasai Thrust Kick",
        img: "/img/C_Ken_10.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
    ],
    supel: [
      {
        characterName: "Ken",
        comboName: "Dragonlash Flame",
        img: "/img/C_Ken_11.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Ken",
        comboName: "Shippu Jinrai",
        img: "/img/C_Ken_12.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Ken",
        comboName: "Shinryu Reppa",
        img: "/img/C_Ken_13.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Ken",
        comboName: "Quick Dash",
        img: "/img/C_Ken_14.webp",
        arrows: ["/img/Kick.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Ken",
        comboName: "Emergency Stop",
        img: "/img/C_Ken_15.webp",
        left: 1,
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Ken",
        comboName: "Thunder Kick",
        img: "/img/C_Ken_16.webp",
        left: 1,
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Ken",
        comboName: "Forward Step Kick",
        img: "/img/C_Ken_17.webp",
        left: 2,
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Ken",
        comboName: "Chin Buster",
        img: "/img/C_Ken_18.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Ken",
        comboName: "Triple Flash Kicks",
        img: "/img/C_Ken_19.webp",
        arrows: ["/img/Kick.webp", "/img/Kick.webp", "/img/Kick.webp"],
      },
    ],
    throws: [
      {
        characterName: "Ken",
        comboName: "Knee Strikes",
        img: "/img/C_Ken_20.webp",
        arrows: [
          "/img/N.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Ken",
        comboName: "Hell Wheel",
        img: "/img/C_Ken_21.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    common: [
      {
        characterName: "Ken",
        comboName: "Drive Impact Flame Strike",
        img: "/img/C_Ken_22.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Ken",
        comboName: "Drive Reversal Lightning Crack",
        img: "/img/C_Ken_23.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Ken",
        comboName: "Drive Parry",
        img: "/img/C_Ken_24.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Ken",
        comboName: "Parry Drive Rush",
        img: "/img/C_Ken_25.webp",
        left: 2,
        energy: "/img/E_0,5.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Ken",
        comboName: "Cancel Drive Rush",
        img: "/img/C_Ken_26.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
