export const data = [
  {
    name: "Kimberly",
    img: "test",
    zoom: 8,
    main: 7,
    imgActive: "/img/KimberlyA.webp",
    imgNotActive: "/img/KimberlyN.webp",
    describe:
      "Uninvited student to Guy, the 39th successor to Bushinryu. Kimberly had an ordinary upbringing, but she's a genuine prodigy who graduated college early...and now wants to be a ninja. Loves '80s pop culture.",
    hates: "Tear-jerker movies",
    likes: "80's music, sneakers, large numbers",
    height: "5'6",
    weight: "134 lbs",
    img1: "/img/O_Kimberly_1.webp",
    img2: "/img/O_Kimberly_2.webp",
    out1: [
      "/img/KimberlyF_01.webp",
      "/img/KimberlyF_02.webp",
      "/img/KimberlyF_03.webp",
      "/img/KimberlyF_04.webp",
      "/img/KimberlyF_05.webp",
      "/img/KimberlyF_06.webp",
      "/img/KimberlyF_07.webp",
      "/img/KimberlyF_08.webp",
      "/img/KimberlyF_09.webp",
    ],
    out2: [
      "/img/KimberlyS_01.webp",
      "/img/KimberlyS_02.webp",
      "/img/KimberlyS_03.webp",
      "/img/KimberlyS_04.webp",
      "/img/KimberlyS_05.webp",
      "/img/KimberlyS_06.webp",
      "/img/KimberlyS_07.webp",
      "/img/KimberlyS_08.webp",
      "/img/KimberlyS_09.webp",
      "/img/KimberlyS_10.webp",
    ],
    video: [
      {
        characterName: "Kimberly",
        comboName: "Bushin Senpukyaku",
        video: "/img/V_Kimberly_1.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Aerial Bushin Senpukyaku",
        video: "/img/V_Kimberly_2.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Sprint",
        video: "/img/V_Kimberly_3.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Emergency Stop",
        video: "/img/V_Kimberly_4.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Torso Cleaver",
        video: "/img/V_Kimberly_5.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Shadow Slide",
        video: "/img/V_Kimberly_6.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Neck Hunter",
        video: "/img/V_Kimberly_7.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Arc Step",
        video: "/img/V_Kimberly_8.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Izuma Otoshi",
        video: "/img/V_Kimberly_9.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Hojin Kick",
        video: "/img/V_Kimberly_10.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Vagabond Edge",
        video: "/img/V_Kimberly_11.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Hidden Variable",
        video: "/img/V_Kimberly_12.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Genius at Play",
        video: "/img/V_Kimberly_13.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Shuriken Bomb",
        video: "/img/V_Kimberly_14.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Shuriken Bomb Spread",
        video: "/img/V_Kimberly_15.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Nue Twister",
        video: "/img/V_Kimberly_16.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Beats",
        video: "/img/V_Kimberly_17.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Thunderous Beats",
        video: "/img/V_Kimberly_18.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Scramble",
        video: "/img/V_Kimberly_19.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Soaring Bushin Scramble",
        video: "/img/V_Kimberly_20.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Ninjastar Cypher",
        video: "/img/V_Kimberly_21.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Water Slicer Slide",
        video: "/img/V_Kimberly_22.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Windmill Kick",
        video: "/img/V_Kimberly_23.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Hisen Kick",
        video: "/img/V_Kimberly_24.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Step Up",
        video: "/img/V_Kimberly_25.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Elbow Drop",
        video: "/img/V_Kimberly_26.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Tiger Fangs",
        video: "/img/V_Kimberly_27.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Prism Strike",
        video: "/img/V_Kimberly_28.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Hellchain",
        video: "/img/V_Kimberly_29.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Hellchain Throw",
        video: "/img/V_Kimberly_30.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Ripcord Throw",
        video: "/img/V_Kimberly_31.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Bell Ringer",
        video: "/img/V_Kimberly_32.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Drive impact Stedfast Strike",
        video: "/img/V_Kimberly_33.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Drive Reversal Shapeless State",
        video: "/img/V_Kimberly_34.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Drive Parry",
        video: "/img/V_Kimberly_35.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Parry Drive Rush",
        video: "/img/V_Kimberly_36.mp4",
      },
      {
        characterName: "Kimberly",
        comboName: "Cancel Drive Rush",
        video: "/img/V_Kimberly_37.mp4",
      },
    ],
    special: [
      {
        characterName: "Kimberly",
        comboName: "Bushin Senpukyaku",
        img: "/img/C_Kimberly_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Aerial Bushin Senpukyaku",
        img: "/img/C_Kimberly_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Sprint",
        img: "/img/C_Kimberly_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Emergency Stop",
        img: "/img/C_Kimberly_4.webp",
        left: 1,
        arrows: ["/img/Punch.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Torso Cleaver",
        img: "/img/C_Kimberly_5.webp",
        left: 1,
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Shadow Slide",
        img: "/img/C_Kimberly_6.webp",
        left: 1,
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Neck Hunter",
        img: "/img/C_Kimberly_7.webp",
        left: 1,
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Arc Step",
        img: "/img/C_Kimberly_8.webp",
        left: 1,
        arrows: ["Automatically activates after"],
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Izuma Otoshi",
        img: "/img/C_Kimberly_9.webp",
        left: 1,
        arrows: ["/img/Punch.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Hojin Kick",
        img: "/img/C_Kimberly_10.webp",
        left: 2,
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Vagabond Edge",
        img: "/img/C_Kimberly_11.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Hidden Variable",
        img: "/img/C_Kimberly_12.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Genius at Play",
        img: "/img/C_Kimberly_13.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Shuriken Bomb",
        img: "/img/C_Kimberly_14.webp",
        left: 1,
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Shuriken Bomb Spread",
        left: 2,
        img: "/img/C_Kimberly_15.webp",
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Nue Twister",
        img: "/img/C_Kimberly_16.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    supel: [
      {
        characterName: "Kimberly",
        comboName: "Bushin Beats",
        img: "/img/C_Kimberly_17.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Thunderous Beats",
        img: "/img/C_Kimberly_18.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Scramble",
        img: "/img/C_Kimberly_19.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Soaring Bushin Scramble",
        img: "/img/C_Kimberly_20.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Ninjastar Cypher",
        img: "/img/C_Kimberly_21.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Kimberly",
        comboName: "Water Slicer Slide",
        img: "/img/C_Kimberly_22.webp",
        arrows: ["/img/Dr.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Windmill Kick",
        img: "/img/C_Kimberly_23.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Hisen Kick",
        img: "/img/C_Kimberly_24.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Step Up",
        left: 2,
        img: "/img/C_Kimberly_25.webp",
        arrows: ["/img/UpL.webp", "/img/Up.webp", "/img/UpR.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Elbow Drop",
        img: "/img/C_Kimberly_26.webp",
        arrows: ["/img/D.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Tiger Fangs",
        img: "/img/C_Kimberly_27.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Prism Strike",
        img: "/img/C_Kimberly_28.webp",
        arrows: [
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Hellchain",
        img: "/img/C_Kimberly_29.webp",
        arrows: [
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Bushin Hellchain Throw",
        img: "/img/C_Kimberly_30.webp",
        arrows: [
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    throws: [
      {
        characterName: "Kimberly",
        comboName: "Ripcord Throw",
        img: "/img/C_Kimberly_31.webp",
        arrows: [
          "/img/N.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Bell Ringer",
        img: "/img/C_Kimberly_32.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    common: [
      {
        characterName: "Kimberly",
        comboName: "Drive impact Stedfast Strike",
        img: "/img/C_Kimberly_33.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Drive Reversal Shapeless State",
        img: "/img/C_Kimberly_34.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Kimberly",
        comboName: "Drive Parry",
        img: "/img/C_Kimberly_35.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Parry Drive Rush",
        left: 2,
        img: "/img/C_Kimberly_36.webp",
        energy: "/img/E_0,5.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Kimberly",
        comboName: "Cancel Drive Rush",
        img: "/img/C_Kimberly_37.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
