export const data = [
  {
    name: "Lily",
    zoom: 1,
    main: 1,
    img: "/img/Lily.webp",
    imgActive: "/img/LilyA.webp",
    imgNotActive: "/img/LilyN.webp",
    describe:
      "A descendant of the Thunderfoot tribe, Lily speaks with the spirits of nature, trusting in their guidance as she travels the globe. Don't judge a book by its cover—her small stature conceals truly titanic power.",
    hates: "Lies",
    likes: "Cameras, birds of prey,",
    height: "5'3",
    weight: "106 lbs",
    img1: "/img/O_Lily_1.webp",
    img2: "/img/O_Lily_2.webp",
    out1: [
      "/img/LilyF_01.webp",
      "/img/LilyF_02.webp",
      "/img/LilyF_03.webp",
      "/img/LilyF_04.webp",
      "/img/LilyF_05.webp",
      "/img/LilyF_06.webp",
      "/img/LilyF_07.webp",
      "/img/LilyF_08.webp",
      "/img/LilyF_09.webp",
    ],
    out2: [
      "/img/LilyS_01.webp",
      "/img/LilyS_02.webp",
      "/img/LilyS_03.webp",
      "/img/LilyS_04.webp",
      "/img/LilyS_05.webp",
      "/img/LilyS_06.webp",
      "/img/LilyS_07.webp",
      "/img/LilyS_08.webp",
      "/img/LilyS_09.webp",
      "/img/LilyS_10.webp",
    ],
    video: [
      {
        characterName: "Lily",
        comboName: "Condor Wild",
        video: "/img/V_Lily_1.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Condor Spire",
        video: "/img/V_Lily_2.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Tomahawk Buster",
        video: "/img/V_Lily_3.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Condor Dive",
        video: "/img/V_Lily_4.mp4",
      },
      {
        characterName: "Lily",
        comboName: "OD",
        video: "/img/V_Lily_5.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Mexican Typhoon",
        video: "/img/V_Lily_6.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Breezing Hawk",
        video: "/img/V_Lily_7.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Thunderbird",
        video: "/img/V_Lily_8.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Soaring",
        video: "/img/V_Lily_9.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Raging Typhoon",
        video: "/img/V_Lily_10.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Ridge Thurs",
        video: "/img/V_Lily_11.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Horn Breaker",
        video: "/img/V_Lily_12.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Great Spin",
        video: "/img/V_Lily_13.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Double Arrow",
        video: "/img/V_Lily_14.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Desert Storm",
        video: "/img/V_Lily_15.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Canyon Throw",
        video: "/img/V_Lily_16.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Falling Cliff",
        video: "/img/V_Lily_17.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Drive Ipmact",
        video: "/img/V_Lily_18.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Drive Reversal",
        video: "/img/V_Lily_19.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Drive Parry",
        video: "/img/V_Lily_20.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Parry Drive",
        video: "/img/V_Lily_21.mp4",
      },
      {
        characterName: "Lily",
        comboName: "Cancel Drive",
        video: "/img/V_Lily_22.mp4",
      },
    ],
    special: [
      {
        characterName: "Lily",
        comboName: "Condor Wild",
        img: "/img/C_Lily_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Lily",
        comboName: "Condor Spire",
        img: "/img/C_Lily_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Lily",
        comboName: "Tomahawk Buster",
        img: "/img/C_Lily_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Lily",
        comboName: "Condor Dive",
        img: "/img/C_Lily_4.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Lily",
        comboName: "OD",
        img: "/img/C_Lily_5.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Lily",
        comboName: "Mexican Typhoon",
        img: "/img/C_Lily_6.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/G.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
    ],
    supel: [
      {
        characterName: "Lily",
        comboName: "Breezing Hawk",
        img: "/img/C_Lily_7.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Lily",
        comboName: "Thunderbird",
        img: "/img/C_Lily_8.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Lily",
        comboName: "Soaring",
        img: "/img/C_Lily_9.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Lily",
        comboName: "Raging Typhoon",
        img: "/img/C_Lily_10.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Lily",
        comboName: "Ridge Thurs",
        img: "/img/C_Lily_11.webp",
        arrows: ["/img/Dr.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Lily",
        comboName: "Horn Breaker",
        img: "/img/C_Lily_12.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Lily",
        comboName: "Great Spin",
        img: "/img/C_Lily_13.webp",
        arrows: ["/img/D.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Lily",
        comboName: "Double Arrow",
        img: "/img/C_Lily_14.webp",
        arrows: ["/img/Punch.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Lily",
        comboName: "Desert Storm",
        img: "/img/C_Lily_15.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    throws: [
      {
        characterName: "Lily",
        comboName: "Canyon Throw",
        img: "/img/C_Lily_16.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Lily",
        comboName: "Falling Cliff",
        img: "/img/C_Lily_17.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    common: [
      {
        characterName: "Lily",
        comboName: "Drive Ipmact",
        img: "/img/C_Lily_18.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Lily",
        comboName: "Drive Reversal",
        img: "/img/C_Lily_19.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Lily",
        comboName: "Drive Parry",
        img: "/img/C_Lily_20.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Lily",
        comboName: "Parry Drive",
        left: 2,
        img: "/img/C_Lily_21.webp",
        energy: "/img/E_0,5.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Lily",
        comboName: "Cancel Drive",
        img: "/img/C_Lily_22.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
