export const data = [
  {
    name: "Luke",
    imgActive: "/img/LukeA.webp",
    img: "test",
    zoom: 9,
    main: 5,
    imgNotActive: "/img/LukeN.webp",
    describe:
      "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    hates: "Horror games",
    likes: "Travelling, PC games, wacky T-shirts",
    height: "6'1",
    weight: "198 lbs",
    img1: "/img/O_Luke_1.webp",
    img2: "/img/O_Luke_2.webp",
    out1: [
      "/img/LukeF_01.webp",
      "/img/LukeF_02.webp",
      "/img/LukeF_03.webp",
      "/img/LukeF_04.webp",
      "/img/LukeF_05.webp",
      "/img/LukeF_06.webp",
      "/img/LukeF_07.webp",
      "/img/LukeF_08.webp",
      "/img/LukeF_09.webp",
    ],
    out2: [
      "/img/LukeS_01.webp",
      "/img/LukeS_02.webp",
      "/img/LukeS_03.webp",
      "/img/LukeS_04.webp",
      "/img/LukeS_05.webp",
      "/img/LukeS_06.webp",
      "/img/LukeS_07.webp",
      "/img/LukeS_08.webp",
      "/img/LukeS_09.webp",
      "/img/LukeS_10.webp",
    ],
    video: [
      {
        characterName: "Luke",
        comboName: "Sand Blast",
        video: "/img/V_Luke_1.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Fatal Shot",
        video: "/img/V_Luke_2.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Flash Knuckle",
        video: "/img/V_Luke_3.mp4",
      },
      {
        characterName: "Luke",
        comboName: "DDT",
        video: "/img/V_Luke_4.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Aerial Flash Knuckle",
        video: "/img/V_Luke_5.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Avenger",
        video: "/img/V_Luke_6.mp4",
      },
      {
        characterName: "Luke",
        comboName: "No Chaser",
        video: "/img/V_Luke_7.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Impaler",
        video: "/img/V_Luke_8.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Rising Uppercut",
        video: "/img/V_Luke_9.mp4",
      },
      {
        characterName: "Luke",
        comboName: "slam Dunk",
        video: "/img/V_Luke_10.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Vulcan Blast",
        video: "/img/V_Luke_11.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Eraser",
        video: "/img/V_Luke_12.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Pale Rider",
        video: "/img/V_Luke_13.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Rawhide",
        video: "/img/V_Luke_14.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Suppressor",
        video: "/img/V_Luke_15.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Outlaw Kick",
        video: "/img/V_Luke_16.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Double Impact",
        video: "/img/V_Luke_17.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Triple Impact",
        video: "/img/V_Luke_18.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Nose Breaker",
        video: "/img/V_Luke_19.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Snapback Combo",
        video: "/img/V_Luke_20.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Sweeper",
        video: "/img/V_Luke_21.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Scrapper",
        video: "/img/V_Luke_22.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Drive Impact Muzzle Flash",
        video: "/img/V_Luke_23.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Drive Reversal Battering Ram",
        video: "/img/V_Luke_24.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Drive Parry",
        video: "/img/V_Luke_25.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Parry Drive Rush",
        video: "/img/V_Luke_26.mp4",
      },
      {
        characterName: "Luke",
        comboName: "Cancel Drive Rush",
        video: "/img/V_Luke_27.mp4",
      },
    ],
    special: [
      {
        characterName: "Luke",
        comboName: "Sand Blast",
        img: "/img/C_Luke_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Luke",
        comboName: "Fatal Shot",
        img: "/img/C_Luke_2.webp",
        left: 2,
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Luke",
        comboName: "Flash Knuckle",
        img: "/img/C_Luke_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Luke",
        comboName: "DDT",
        img: "/img/C_Luke_4.webp",
        left: 2,
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Luke",
        comboName: "Aerial Flash Knuckle",
        img: "/img/C_Luke_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Luke",
        comboName: "Avenger",
        img: "/img/C_Luke_6.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Luke",
        comboName: "No Chaser",
        img: "/img/C_Luke_7.webp",
        left: 1,
        arrows: ["/img/Punch.webp"],
      },
      {
        characterName: "Luke",
        comboName: "Impaler",
        img: "/img/C_Luke_8.webp",
        left: 2,
        arrows: ["/img/Kick.webp"],
      },
      {
        characterName: "Luke",
        comboName: "Rising Uppercut",
        img: "/img/C_Luke_9.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Luke",
        comboName: "slam Dunk",
        img: "/img/C_Luke_10.webp",
        energy: "/img/E_1.webp",
        left: 2,
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
    ],
    supel: [
      {
        characterName: "Luke",
        comboName: "Vulcan Blast",
        img: "/img/C_Luke_11.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Luke",
        comboName: "Eraser",
        img: "/img/C_Luke_12.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Luke",
        comboName: "Pale Rider",
        img: "/img/C_Luke_13.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Luke",
        comboName: "Rawhide",
        img: "/img/C_Luke_14.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Luke",
        comboName: "Suppressor",
        img: "/img/C_Luke_15.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Luke",
        comboName: "Outlaw Kick",
        img: "/img/C_Luke_16.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Luke",
        comboName: "Double Impact",
        img: "/img/C_Luke_17.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Luke",
        comboName: "Triple Impact",
        img: "/img/C_Luke_18.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Luke",
        comboName: "Nose Breaker",
        img: "/img/C_Luke_19.webp",
        arrows: [
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        img: "/img/C_Luke_20.webp",
        characterName: "Luke",
        comboName: "Snapback Combo",
        arrows: [
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    throws: [
      {
        characterName: "Luke",
        comboName: "Sweeper",
        img: "/img/C_Luke_21.webp",
        arrows: [
          "/img/N.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Luke",
        comboName: "Scrapper",
        img: "/img/C_Luke_22.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    common: [
      {
        characterName: "Luke",
        comboName: "Drive Impact Muzzle Flash",
        img: "/img/C_Luke_23.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Luke",
        comboName: "Drive Reversal Battering Ram",
        img: "/img/C_Luke_24.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Luke",
        comboName: "Drive Parry",
        img: "/img/C_Luke_25.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Luke",
        comboName: "Parry Drive Rush",
        img: "/img/C_Luke_26.webp",
        left: 2,
        energy: "/img/E_0,5.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Luke",
        comboName: "Cancel Drive Rush",
        img: "/img/C_Luke_27.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
