export const data = [
  {
    name: "Manon",
    imgActive: "/img/ManonA.webp",
    img: "test",
    zoom: 5,
    main: 6,
    imgNotActive: "/img/ManonN.webp",
    describe:
      "A super model and world champion judoka, Manon is an idealist, forever seeking self-improvement in the pursuit of beauty. She struts the catwalk of street fighting to become the world's strongest model.",
    hates: "Crowds, chatterboxes",
    likes: "The color gold, cosmetics, her family",
    height: "5'9",
    weight: "129 lbs",
    img1: "/img/O_Manon_1.webp",
    img2: "/img/O_Manon_2.webp",
    out1: [
      "/img/ManonF_01.webp",
      "/img/ManonF_02.webp",
      "/img/ManonF_03.webp",
      "/img/ManonF_04.webp",
      "/img/ManonF_05.webp",
      "/img/ManonF_06.webp",
      "/img/ManonF_07.webp",
      "/img/ManonF_08.webp",
      "/img/ManonF_09.webp",
    ],
    out2: [
      "/img/ManonS_01.webp",
      "/img/ManonS_02.webp",
      "/img/ManonS_03.webp",
      "/img/ManonS_04.webp",
      "/img/ManonS_05.webp",
      "/img/ManonS_06.webp",
      "/img/ManonS_07.webp",
      "/img/ManonS_08.webp",
      "/img/ManonS_09.webp",
      "/img/ManonS_10.webp",
    ],
    video: [
      {
        characterName: "Manon",
        comboName: "Manege Dore",
        video: "/img/V_Manon_1.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Rond-point",
        video: "/img/V_Manon_2.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Degage",
        video: "/img/V_Manon_3.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Renverse",
        video: "/img/V_Manon_4.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Grand Fouetee",
        video: "/img/V_Manon_5.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Arabesque",
        video: "/img/V_Manon_6.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Etoile",
        video: "/img/V_Manon_7.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Pas de Deux",
        video: "/img/V_Manon_8.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Reverence",
        video: "/img/V_Manon_9.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Tomoe Derriere",
        video: "/img/V_Manon_10.mp4",
      },
      {
        characterName: "Manon",
        comboName: "A Terre",
        video: "/img/V_Manon_11.mp4",
      },
      {
        characterName: "Manon",
        comboName: "En Haut",
        video: "/img/V_Manon_12.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Temps Lie",
        video: "/img/V_Manon_13.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Allonge",
        video: "/img/V_Manon_14.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Ouchi Gari",
        video: "/img/V_Manon_15.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Uchi Mata",
        video: "/img/V_Manon_16.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Drive Impact Glissade",
        video: "/img/V_Manon_17.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Drive Reversal Ecarte",
        video: "/img/V_Manon_18.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Drive Parry Manon",
        video: "/img/V_Manon_19.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Parry Drive Rush Manon",
        video: "/img/V_Manon_20.mp4",
      },
      {
        characterName: "Manon",
        comboName: "Cancel Drive Manon",
        video: "/img/V_Manon_21.mp4",
      },
    ],
    special: [
      {
        characterName: "Manon",
        comboName: "Manege Dore",
        img: "/img/C_Manon_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Dr.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Manon",
        comboName: "Rond-point",
        img: "/img/C_Manon_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Manon",
        comboName: "Degage",
        img: "/img/C_Manon_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Manon",
        comboName: "Renverse",
        img: "/img/C_Manon_4.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Manon",
        comboName: "Grand Fouetee",
        img: "/img/C_Manon_5.webp",
        left: 2,
        arrows: ["/img/Kick.webp"],
      },
    ],
    supel: [
      {
        characterName: "Manon",
        comboName: "Arabesque",
        img: "/img/C_Manon_6.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Manon",
        comboName: "Etoile",
        img: "/img/C_Manon_7.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Manon",
        comboName: "Pas de Deux",
        img: "/img/C_Manon_8.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Manon",
        comboName: "Reverence",
        img: "/img/C_Manon_9.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Manon",
        comboName: "Tomoe Derriere",
        img: "/img/C_Manon_10.webp",
        arrows: ["/img/Dr.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Manon",
        comboName: "A Terre",
        img: "/img/C_Manon_11.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Manon",
        comboName: "En Haut",
        img: "/img/C_Manon_12.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Manon",
        comboName: "Temps Lie",
        img: "/img/C_Manon_13.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Manon",
        comboName: "Allonge",
        img: "/img/C_Manon_14.webp",
        arrows: [
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    throws: [
      {
        characterName: "Manon",
        comboName: "Ouchi Gari",
        img: "/img/C_Manon_15.webp",
        arrows: [
          "/img/N.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Manon",
        comboName: "Uchi Mata",
        img: "/img/C_Manon_16.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    common: [
      {
        characterName: "Manon",
        comboName: "Drive Impact Glissade",
        img: "/img/C_Manon_17.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Manon",
        comboName: "Drive Reversal Ecarte",
        img: "/img/C_Manon_18.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Manon",
        comboName: "Drive Parry Manon",
        img: "/img/C_Manon_19.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Manon",
        comboName: "Parry Drive Rush Manon",
        img: "/img/C_Manon_20.webp",
        left: 2,
        energy: "/img/E_0,5.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Manon",
        comboName: "Cancel Drive Manon",
        img: "/img/C_Manon_21.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
