export const data = [
  {
    name: "Marisa",
    zoom: 1,
    main: 5,
    img: "test",
    imgActive: "/img/MarisaA.webp",
    imgNotActive: "/img/MarisaN.webp",
    describe:
      "An up-and-coming jewelry designer from Italy who claims ancestry to ancient Greek warriors. As a child, she was inspired by a vision of the Colosseum in its prime. Today, she seeks glory with a smile—and an eye for beauty.",
    hates: "Heights",
    likes: "Worthy opponents, ossobuco, fine arts",
    height: "6'8",
    weight: "269 lbs",
    img1: "/img/O_Marisa_1.webp",
    img2: "/img/O_Marisa_2.webp",
    out1: [
      "/img/MarisaF_01.webp",
      "/img/MarisaF_02.webp",
      "/img/MarisaF_03.webp",
      "/img/MarisaF_04.webp",
      "/img/MarisaF_05.webp",
      "/img/MarisaF_06.webp",
      "/img/MarisaF_07.webp",
      "/img/MarisaF_08.webp",
      "/img/MarisaF_09.webp",
    ],
    out2: [
      "/img/MarisaS_01.webp",
      "/img/MarisaS_02.webp",
      "/img/MarisaS_03.webp",
      "/img/MarisaS_04.webp",
      "/img/MarisaS_05.webp",
      "/img/MarisaS_06.webp",
      "/img/MarisaS_07.webp",
      "/img/MarisaS_08.webp",
      "/img/MarisaS_09.webp",
      "/img/MarisaS_10.webp",
    ],
    video: [
      {
        characterName: "Marisa",
        comboName: "Gladius",
        video: "/img/V_Marisa_1.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Dimachaerus",
        video: "/img/V_Marisa_2.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Phalanx",
        video: "/img/V_Marisa_3.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Quadriga",
        video: "/img/V_Marisa_4.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Scutum",
        video: "/img/V_Marisa_5.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Tonitrus",
        video: "/img/V_Marisa_6.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Procella",
        video: "/img/V_Marisa_7.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Enfold",
        video: "/img/V_Marisa_8.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Javelin of Marisa",
        video: "/img/V_Marisa_9.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Meteorite",
        video: "/img/V_Marisa_10.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Goddess of the Hunt",
        video: "/img/V_Marisa_11.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Marisa Style",
        video: "/img/V_Marisa_12.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Light Two Hitter",
        video: "/img/V_Marisa_13.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Medium Two Hitter",
        video: "/img/V_Marisa_14.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Heavy Two Hitter",
        video: "/img/V_Marisa_15.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Volare Combo",
        video: "/img/V_Marisa_16.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Caelum Arc",
        video: "/img/V_Marisa_17.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Magna Bunker",
        video: "/img/V_Marisa_18.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Novacula Swipe",
        video: "/img/V_Marisa_19.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Novacula Thrust",
        video: "/img/V_Marisa_20.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Malleus Breaker",
        video: "/img/V_Marisa_21.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Falx Crusher",
        video: "/img/V_Marisa_22.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Mouted Grace",
        video: "/img/V_Marisa_23.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Ponte Milvio",
        video: "/img/V_Marisa_24.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Drive Impact Secutor",
        video: "/img/V_Marisa_25.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Drive Reversal Love Tap",
        video: "/img/V_Marisa_26.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Drive Parry Marisa",
        video: "/img/V_Marisa_27.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Parry Drive Rush Marisa",
        video: "/img/V_Marisa_28.mp4",
      },
      {
        characterName: "Marisa",
        comboName: "Cancel Drive Rush",
        video: "/img/V_Marisa_29.mp4",
      },
    ],
    special: [
      {
        characterName: "Marisa",
        comboName: "Gladius",
        img: "/img/C_Marisa_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Marisa",
        comboName: "Dimachaerus",
        img: "/img/C_Marisa_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Marisa",
        comboName: "Phalanx",
        img: "/img/C_Marisa_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Marisa",
        comboName: "Quadriga",
        img: "/img/C_Marisa_4.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Marisa",
        comboName: "Scutum",
        img: "/img/C_Marisa_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Marisa",
        comboName: "Tonitrus",
        img: "/img/C_Marisa_6.webp",
        left: 1,
        arrows: ["/img/Punch.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Marisa",
        comboName: "Procella",
        left: 1,
        arrows: ["/img/Kick.webp"],
        img: "/img/C_Marisa_7.webp",
      },
      {
        characterName: "Marisa",
        comboName: "Enfold",
        img: "/img/C_Marisa_8.webp",
        left: 2,
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
    ],
    supel: [
      {
        characterName: "Marisa",
        comboName: "Javelin of Marisa",
        img: "/img/C_Marisa_9.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Marisa",
        comboName: "Meteorite",
        img: "/img/C_Marisa_10.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Marisa",
        comboName: "Goddess of the Hunt",
        img: "/img/C_Marisa_11.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Marisa",
        comboName: "Marisa Style",
        img: "/img/C_Marisa_12.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Marisa",
        comboName: "Light Two Hitter",
        img: "/img/C_Marisa_13.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Marisa",
        comboName: "Medium Two Hitter",
        img: "/img/C_Marisa_14.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Marisa",
        comboName: "Heavy Two Hitter",
        img: "/img/C_Marisa_15.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Marisa",
        comboName: "Volare Combo",
        img: "/img/C_Marisa_16.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Marisa",
        comboName: "Caelum Arc",
        img: "/img/C_Marisa_17.webp",
        arrows: ["/img/D.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Marisa",
        comboName: "Magna Bunker",
        img: "/img/C_Marisa_18.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Marisa",
        comboName: "Novacula Swipe",
        img: "/img/C_Marisa_19.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Marisa",
        comboName: "Novacula Thrust",
        img: "/img/C_Marisa_20.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Marisa",
        comboName: "Malleus Breaker",
        img: "/img/C_Marisa_21.webp",
        arrows: [
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Marisa",
        comboName: "Falx Crusher",
        img: "/img/C_Marisa_22.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    throws: [
      {
        characterName: "Marisa",
        comboName: "Mouted Grace",
        img: "/img/C_Marisa_23.webp",
        arrows: [
          "/img/N.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Marisa",
        comboName: "Ponte Milvio",
        img: "/img/C_Marisa_24.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    common: [
      {
        characterName: "Marisa",
        comboName: "Drive Impact Secutor",
        img: "/img/C_Marisa_25.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Marisa",
        comboName: "Drive Reversal Love Tap",
        img: "/img/C_Marisa_26.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Marisa",
        comboName: "Drive Parry Marisa",
        img: "/img/C_Marisa_27.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Marisa",
        comboName: "Parry Drive Rush Marisa",
        img: "/img/C_Marisa_28.webp",
        energy: "/img/E_0,5.webp",
        left: 2,
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Marisa",
        comboName: "Cancel Drive Rush",
        img: "/img/C_Marisa_29.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
