export const data = [
  {
    name: "Ryu",
    img: "test",
    zoom: 2,
    main: 6,
    imgActive: "/img/RyuA.webp",
    imgNotActive: "/img/RyuN.webp",
    describe:
      "Ever training, this martial artist seeks true strength. Well-mannered and sincere, Ryu travels the globe in search of worthy opponents. Having overcome the Satsui no Hado, he now seeks yet greater heights.",
    hates: "Spiders",
    likes: "Martial arts",
    height: "5'9",
    weight: "187 lbs",
    img1: "/img/O_Ryu_1.webp",
    img2: "/img/O_Ryu_2.webp",
    out1: [
      "/img/RyuF_01.webp",
      "/img/RyuF_02.webp",
      "/img/RyuF_03.webp",
      "/img/RyuF_04.webp",
      "/img/RyuF_05.webp",
      "/img/RyuF_06.webp",
      "/img/RyuF_07.webp",
      "/img/RyuF_08.webp",
      "/img/RyuF_09.webp",
    ],
    out2: [
      "/img/RyuS_01.webp",
      "/img/RyuS_02.webp",
      "/img/RyuS_03.webp",
      "/img/RyuS_04.webp",
      "/img/RyuS_05.webp",
      "/img/RyuS_06.webp",
      "/img/RyuS_07.webp",
      "/img/RyuS_08.webp",
      "/img/RyuS_09.webp",
      "/img/RyuS_10.webp",
    ],
    video: [
      {
        characterName: "Ryu",
        comboName: "Hadoken",
        video: "/img/V_Ryu_1.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Shoryken",
        video: "/img/V_Ryu_2.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Tatsumaki Senpu-kyaku",
        video: "/img/V_Ryu_3.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Aerial Tatsumaki Senpu",
        video: "/img/V_Ryu_4.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "High Blade Kick",
        video: "/img/V_Ryu_5.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Hashogeki",
        video: "/img/V_Ryu_6.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Denjin Charge",
        video: "/img/V_Ryu_7.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Shinku Hadoken",
        video: "/img/V_Ryu_8.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Shin Hashogeki",
        video: "/img/V_Ryu_9.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Shin Shoryuken",
        video: "/img/V_Ryu_10.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Collarbone Breaker",
        video: "/img/V_Ryu_11.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Solar Plexus Strike",
        video: "/img/V_Ryu_12.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Short Uppercut",
        video: "/img/V_Ryu_13.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Axe Kick",
        video: "/img/V_Ryu_14.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Whirlwind Kick",
        video: "/img/V_Ryu_15.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "High Double Strike",
        video: "/img/V_Ryu_16.mp4",
      },
      {
        video: "/img/V_Ryu_17.mp4",
        characterName: "Ryu",
        comboName: "Fuwa Triple Strike",
      },
      {
        characterName: "Ryu",
        comboName: "Shoulder Throw",
        video: "/img/V_Ryu_18.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Somersault Throw",
        video: "/img/V_Ryu_19.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Drive Impact Shingeki",
        video: "/img/V_Ryu_20.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Drive Reversal Chest Strike",
        video: "/img/V_Ryu_21.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Drive Parry",
        video: "/img/V_Ryu_22.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Parry Drive Rush",
        video: "/img/V_Ryu_23.mp4",
      },
      {
        characterName: "Ryu",
        comboName: "Cancel Drive Rush",
        video: "/img/V_Ryu_24.mp4",
      },
    ],
    special: [
      {
        characterName: "Ryu",
        comboName: "Hadoken",
        img: "/img/C_Ryu_1.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Ryu",
        comboName: "Shoryken",
        img: "/img/C_Ryu_2.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Ryu",
        comboName: "Tatsumaki Senpu-kyaku",
        img: "/img/C_Ryu_3.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Ryu",
        comboName: "Aerial Tatsumaki Senpu",
        img: "/img/C_Ryu_4.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Ryu",
        comboName: "High Blade Kick",
        img: "/img/C_Ryu_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Ryu",
        comboName: "Hashogeki",
        img: "/img/C_Ryu_6.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Ryu",
        comboName: "Denjin Charge",
        img: "/img/C_Ryu_7.webp",
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    supel: [
      {
        characterName: "Ryu",
        comboName: "Shinku Hadoken",
        img: "/img/C_Ryu_8.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Ryu",
        comboName: "Shin Hashogeki",
        img: "/img/C_Ryu_9.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Ryu",
        comboName: "Shin Shoryuken",
        img: "/img/C_Ryu_10.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Ryu",
        comboName: "Collarbone Breaker",
        img: "/img/C_Ryu_11.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Ryu",
        comboName: "Solar Plexus Strike",
        img: "/img/C_Ryu_12.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Ryu",
        comboName: "Short Uppercut",
        img: "/img/C_Ryu_13.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Ryu",
        comboName: "Axe Kick",
        img: "/img/C_Ryu_14.webp",
        arrows: ["/img/L.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Ryu",
        comboName: "Whirlwind Kick",
        img: "/img/C_Ryu_15.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Ryu",
        comboName: "High Double Strike",
        img: "/img/C_Ryu_16.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Ryu",
        comboName: "Fuwa Triple Strike",
        img: "/img/C_Ryu_17.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp", "/img/Kick.webp"],
      },
    ],
    throws: [
      {
        characterName: "Ryu",
        comboName: "Shoulder Throw",
        img: "/img/C_Ryu_18.webp",
        arrows: [
          "/img/N.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Ryu",
        comboName: "Somersault Throw",
        img: "/img/C_Ryu_19.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    common: [
      {
        characterName: "Ryu",
        comboName: "Drive Impact Shingeki",
        img: "/img/C_Ryu_20.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Ryu",
        comboName: "Drive Reversal Chest Strike",
        img: "/img/C_Ryu_21.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        img: "/img/C_Ryu_22.webp",
        characterName: "Ryu",
        comboName: "Drive Parry",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Ryu",
        comboName: "Parry Drive Rush",
        left: 2,
        img: "/img/C_Ryu_23.webp",
        energy: "/img/E_0,5.webp",
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Ryu",
        comboName: "Cancel Drive Rush",
        img: "/img/C_Ryu_24.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
