export const data = [
  {
    name: "Zangief",
    img: "test",
    // zoom: 3,
    // main: 3,
    imgActive: "/img/ZangiefA.webp",
    imgNotActive: "/img/ZangiefN.webp",
    describe:
      "A colossal wrestler nicknamed the Red Cyclone. Zangief is dedicated to physical improvement and instructing his students.",
    hates: "Projectiles (Hadokens, etc.)",
    likes: "Wrestling, Cossack dancing",
    height: "7'0",
    weight: "399 lbs",
    img1: "/img/O_Zangief_1.webp",
    img2: "/img/O_Zangief_2.webp",
    out1: [
      "/img/ZangiefF_01.webp",
      "/img/ZangiefF_02.webp",
      "/img/ZangiefF_03.webp",
      "/img/ZangiefF_04.webp",
      "/img/ZangiefF_05.webp",
      "/img/ZangiefF_06.webp",
      "/img/ZangiefF_07.webp",
      "/img/ZangiefF_08.webp",
      "/img/ZangiefF_09.webp",
    ],
    out2: [
      "/img/ZangiefS_01.webp",
      "/img/ZangiefS_02.webp",
      "/img/ZangiefS_03.webp",
      "/img/ZangiefS_04.webp",
      "/img/ZangiefS_05.webp",
      "/img/ZangiefS_06.webp",
      "/img/ZangiefS_07.webp",
      "/img/ZangiefS_08.webp",
      "/img/ZangiefS_09.webp",
      "/img/ZangiefS_10.webp",
    ],
    video: [
      {
        characterName: "Zangief",
        comboName: "Double Lariat",
        video: "/img/V_Zangief_1.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Screw Piledriver",
        video: "/img/V_Zangief_2.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Borscht Dynamite",
        video: "/img/V_Zangief_3.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Russian Suplex",
        video: "/img/V_Zangief_4.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Siberian Express",
        video: "/img/V_Zangief_5.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Tundra Storm",
        video: "/img/V_Zangief_6.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Aerial Slam",
        video: "/img/V_Zangief_7.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Cyclone Lariat",
        video: "/img/V_Zangief_8.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Bolshoi Storm",
        video: "/img/V_Zangief_9.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Hellstab",
        video: "/img/V_Zangief_10.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Knee Hammer",
        video: "/img/V_Zangief_11.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Headbutt",
        video: "/img/V_Zangief_12.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Cyclone Wheel",
        video: "/img/V_Zangief_13.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Smetana Dropkick",
        video: "/img/V_Zangief_14.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Flying Body",
        video: "/img/V_Zangief_15.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Flying Headbutt",
        video: "/img/V_Zangief_16.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Machine Gun",
        video: "/img/V_Zangief_17.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Power Stomps",
        video: "/img/V_Zangief_18.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Bodyslam",
        video: "/img/V_Zangief_19.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Capture Suplex",
        video: "/img/V_Zangief_20.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Geman Suplex",
        video: "/img/V_Zangief_21.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Spinebuster",
        video: "/img/V_Zangief_22.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Ukraine Drop",
        video: "/img/V_Zangief_23.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Braine Buster",
        video: "/img/V_Zangief_24.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Drive Impact",
        video: "/img/V_Zangief_25.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Drive Reversal",
        video: "/img/V_Zangief_26.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Drive Parry",
        video: "/img/V_Zangief_27.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Parry Drive",
        video: "/img/V_Zangief_28.mp4",
      },
      {
        characterName: "Zangief",
        comboName: "Cancel Drive",
        video: "/img/V_Zangief_29.mp4",
      },
    ],
    special: [
      {
        characterName: "Zangief",
        comboName: "Double Lariat",
        img: "/img/C_Zangief_1.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Screw Piledriver",
        img: "/img/C_Zangief_2.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/G.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Borscht Dynamite",
        img: "/img/C_Zangief_3.webp",
        energy: "/img/E_2.webp",
        arrows: ["/img/G.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Russian Suplex",
        img: "/img/C_Zangief_4.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Dr.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Zangief",
        comboName: "Siberian Express",
        img: "/img/C_Zangief_5.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Dr.webp",
          "/img/D.webp",
          "/img/Dl.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Zangief",
        comboName: "Tundra Storm",
        img: "/img/C_Zangief_6.webp",
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    supel: [
      {
        characterName: "Zangief",
        comboName: "Aerial Slam",
        img: "/img/C_Zangief_7.webp",
        energy: "/img/EP_1.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Zangief",
        comboName: "Cyclone Lariat",
        img: "/img/C_Zangief_8.webp",
        energy: "/img/EP_2.webp",
        arrows: [
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/D.webp",
          "/img/Dr.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
      {
        characterName: "Zangief",
        comboName: "Bolshoi Storm",
        img: "/img/C_Zangief_9.webp",
        energy: "/img/EP_3.webp",
        arrows: [
          "/img/G.webp",
          "/img/G.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
        ],
      },
    ],
    unique: [
      {
        characterName: "Zangief",
        comboName: "Hellstab",
        img: "/img/C_Zangief_10.webp",
        arrows: ["/img/Dr.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Knee Hammer",
        img: "/img/C_Zangief_11.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Headbutt",
        img: "/img/C_Zangief_12.webp",
        arrows: ["/img/R.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Cyclone Wheel",
        img: "/img/C_Zangief_13.webp",
        arrows: ["/img/R.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Smetana Dropkick",
        img: "/img/C_Zangief_14.webp",
        arrows: ["/img/Dr.webp", "/img/Plus.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Flying Body",
        img: "/img/C_Zangief_15.webp",
        arrows: ["/img/D.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Flying Headbutt",
        img: "/img/C_Zangief_16.webp",
        arrows: ["/img/Up.webp", "/img/Plus.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Machine Gun",
        img: "/img/C_Zangief_17.webp",
        arrows: ["/img/Punch.webp", "/img/Punch.webp", "/img/Punch.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Power Stomps",
        img: "/img/C_Zangief_18.webp",
        arrows: [
          "/img/D.webp",
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    throws: [
      {
        characterName: "Zangief",
        comboName: "Bodyslam",
        img: "/img/C_Zangief_19.webp",
        arrows: [
          "/img/N.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Zangief",
        comboName: "Capture Suplex",
        img: "/img/C_Zangief_20.webp",
        arrows: [
          "/img/L.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Zangief",
        comboName: "Geman Suplex",
        img: "/img/C_Zangief_21.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Zangief",
        comboName: "Spinebuster",
        img: "/img/C_Zangief_22.webp",
        arrows: [
          "/img/Dr.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Zangief",
        comboName: "Ukraine Drop",
        img: "/img/C_Zangief_23.webp",
        arrows: [
          "/img/Dl.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Zangief",
        comboName: "Braine Buster",
        img: "/img/C_Zangief_24.webp",
        arrows: [
          "/img/D.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
    common: [
      {
        characterName: "Zangief",
        comboName: "Drive Impact",
        img: "/img/C_Zangief_25.webp",
        energy: "/img/E_1.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Drive Reversal",
        img: "/img/C_Zangief_26.webp",
        energy: "/img/E_2.webp",
        arrows: [
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
      {
        characterName: "Zangief",
        comboName: "Drive Parry",
        img: "/img/C_Zangief_27.webp",
        energy: "/img/E__.webp",
        arrows: ["/img/Punch.webp", "/img/Kick.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Parry Drive",
        img: "/img/C_Zangief_28.webp",
        energy: "/img/E_0,5.webp",
        left: 2,
        arrows: ["/img/R.webp", "/img/R.webp"],
      },
      {
        characterName: "Zangief",
        comboName: "Cancel Drive",
        img: "/img/C_Zangief_29.webp",
        energy: "/img/E_3.webp",
        arrows: [
          "/img/R.webp",
          "/img/R.webp",
          "/img/Plus.webp",
          "/img/Punch.webp",
          "/img/Kick.webp",
        ],
      },
    ],
  },
];
