import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import s from "./index.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={s.Home}>
        <article className={s.acticle}>
          <section className={s.section}>
            <div className={s.main}>
              <ul className={s.main_ul1}>
                <li>
                  <span>
                    <Image src='/img/PS5.webp' fill={true} alt='' />
                  </span>
                </li>
                <li>
                  <span>
                    <Image src='/img/PS4.webp' fill={true} alt='' />
                  </span>
                </li>
                <li className={s.xbox}>
                  <span>
                    <Image src='/img/XBOX.webp' fill={true} alt='' />
                  </span>
                </li>
                <li className={s.steam}>
                  <span>
                    <Image src='/img/Steam.webp' fill={true} alt='' />
                  </span>
                </li>
              </ul>
              <ul className={s.main_ul2}>
                <li className={s.main_ul2_li}>
                  <a href=''>
                    <span>NEWSLETTER</span>
                  </a>
                </li>
                <li className={s.main_ul2_li2}>
                  <a href=''>
                    <span>StreetFighter6</span>
                  </a>
                </li>
              </ul>
              <div className={s.main_div}>
                <a href=''>
                  <p className={s.main_div_p}>
                    <svg
                      id='a'
                      xmlns='http://www.w3.org/2000/svg'
                      viewBox='0 0 138 30'
                    >
                      <path d='M16.9,13.4c-0.1,0.1-1.8,1.8-1.8,1.8s1.7,1.8,1.8,1.8c0,0.1,0.2,0.2,0.2,0.6c0,0.4,0,4.9,0,4.9s0,0.9,0,2.9 c0,0.1,0,0.4-0.1,0.5c-0.5,0.5-3.2,3.2-3.7,3.7c0,0-0.2,0.2-0.5,0.2c-0.1,0-11.8,0-11.8,0s0-23,0-25c0-0.1,0-0.4,0.1-0.5 C1.6,3.7,4.3,1,4.8,0.6c0-0.1,0.2-0.2,0.5-0.2c0.1,0,11.8,0,11.8,0s0,12.3,0,12.5C17.1,13.1,17,13.3,16.9,13.4z M6.7,12.1h4.6V5.7 H6.7V12.1z M6.7,24.2c1.5,0,3.2,0,4.6,0v-6.3H6.7V24.2z'></path>
                      <path d='M25.5,0.4v23.8h4.7V0.4h5.7c0,0,0,24.5,0,24.8c0,0.3-0.1,0.5-0.1,0.5l-3.7,3.7c0,0-0.2,0.2-0.5,0.2c-1.4,0-6.9,0-7.3,0 c-0.4,0-0.7-0.3-0.7-0.3S20.3,26,20,25.7c-0.2-0.2-0.2-0.3-0.2-0.7c0-0.4,0-24.6,0-24.6H25.5z'></path>
                      <path d='M54.2,0.4c0,0,0,8.7,0,9.2c0,0.1-0.1,0.4-0.2,0.7c0,0.1-2.7,6.1-5,11v8.4h-5.7v-8.4c-2.2-4.9-4.9-10.8-5-11 C38.1,9.9,38,9.7,38,9.6c0-0.4,0-9.2,0-9.2h5.7v9.2l2.3,5.4l2.3-5.4V0.4H54.2z'></path>
                      <path d='M79.7,0.4v29.3h-5.4l-5.7-17.6v17.6h-5.4V0.4h5.4l5.7,17.5V0.4H79.7z'></path>
                      <path d='M98.5,0.4c0,0,0,24.6,0,24.8c0,0.3-0.1,0.5-0.1,0.5l-3.7,3.7c0,0-0.2,0.2-0.5,0.2c-1.4,0-6.9,0-7.3,0 c-0.4,0-0.4-0.1-0.7-0.3c-0.2-0.2-3.3-3.3-3.5-3.6c-0.2-0.2-0.2-0.3-0.2-0.7c0-0.4,0-20.2,0-20.4s0.2-0.4,0.2-0.4L86,0.7 c0,0,0.2-0.3,0.7-0.3C87,0.4,98.5,0.4,98.5,0.4z M92.7,5.8h-4.7v18.4h4.7V5.8z'></path>
                      <path d='M127.5,0.4L123,29.7h-7.2L114,15l-1.9,14.7H105l-4.5-29.3h5.6l2.5,20.1l2.5-20.1h5.7l2.6,20.1l2.5-20.1H127.5z'></path>
                      <path d='M131.5,20.8l-0.6-15.4v-5h5.9v5l-0.6,15.4H131.5z M136.5,24.7c0,0.9,0,3.8,0,5h-5.3v-5H136.5z'></path>
                    </svg>
                  </p>
                  <p className={s.main_div_p2}>Available now!</p>
                </a>
              </div>
            </div>
            <div className={s.patch}>
              <p>
                Over<span>2</span>Million Units Sold WorldWide!
              </p>
            </div>
            <p className={s.left}>
              <span>YOUR MOMENT</span> /<span> YOUR FIGHT</span>
            </p>
            <p className={s.right}>
              <span>YOUR MOMENT</span> /<span> YOUR FIGHT</span>
            </p>
            <div className={s.notice}>
              <p>
                <span>Online Play</span>
              </p>
            </div>
            <div className={s.camp}>
              <a href='#'>
                <p className={s.camp_p}>
                  <span>BucklersBoot Camp</span>
                </p>
                <p className={s.camp_p2}>
                  <span>START!</span>
                </p>
              </a>
            </div>
          </section>
          <section className={s.section2}>
            <h1>
              <Image src='/img/LOGO.webp' fill={true} alt='' />
            </h1>
            <div></div>
          </section>
        </article>

        <article className={s.acticle2}>
          <section className={s.Rashid}>
            <div className={s.Rashid_div}>
              <h2>
                <svg
                  id='a'
                  xmlns='http://www.w3.org/2000/svg'
                  viewBox='0 0 431 160'
                >
                  <path d='M70.74,92.34l7.33,48.89h-23.41l-7.17-47.93h-11.78v47.93H12.3V21.64H59.75c1.59,0,1.91,.32,3.03,.96,.96,.8,13.7,13.54,14.65,14.81,.64,.96,.96,1.27,.96,3.03v41.56c0,1.59-.48,3.34-.96,3.82-2.07,2.39-5.1,4.78-6.69,6.53Zm-35.03-22.93h18.95v-25.8h-18.95v25.8Z'></path>
                  <path d='M154.97,21.8v119.43h-23.41v-47.93h-19.11v47.93h-23.41V39.15c0-.48,.16-1.43,.64-1.91,2.07-1.75,13.06-12.9,14.81-14.81,.32-.16,.8-.64,2.39-.64h48.09Zm-23.41,21.98h-19.11v25.64h19.11v-25.64Z'></path>
                  <path d='M183.79,21.8h48.09V59.22h-23.41v-15.61h-19.27v25.8h25.96c.8,0,1.59,.64,1.59,.64l14.17,14.49s.96,.96,.96,2.39v36.31c0,.96-.32,2.07-.8,2.55-2.87,3.03-12.58,12.9-13.38,13.69-1.75,1.75-1.27,1.75-3.82,1.75h-30.89c-1.27,0-1.27-.32-2.71-1.75-.48-.8-11.47-11.78-14.01-14.17-.16-.32-.48-.8-.48-1.27v-20.22h23.41v15.29h19.27v-25.8h-25.96c-.64,0-1.11-.48-1.11-.48l-15.13-15.13s-.48-.32-.48-1.43V39.15c0-.96,.32-1.43,.8-1.91,2.71-2.87,12.9-13.06,13.7-14.01,1.59-1.75,1.11-1.43,3.5-1.43Z'></path>
                  <path d='M283.16,21.8h23.41v119.43h-23.41v-47.93h-17.2v47.93h-23.41V21.8h23.41v47.61h17.2V21.8Z'></path>
                  <path d='M317.39,21.8h23.57v119.43h-23.57V21.8Z'></path>
                  <path d='M351.79,141.23V21.8h47.61c1.59,0,1.59,.16,2.87,.96,.96,.8,13.54,13.54,14.49,14.81,.8,.96,.96,1.12,.96,3.03V123.71c0,.96-.48,1.75-.48,1.75l-14.17,14.49s-1.27,1.27-2.71,1.27h-48.57Zm23.41-22.29h19.11V43.77h-19.11V118.93Z'></path>
                </svg>
                <div></div>
              </h2>
              <p className={s.Rashid_p}>Play Now!</p>
              <p className={s.Rashid_p2}>
                <a href=''>Details</a>
              </p>
            </div>
          </section>
          <section className={s.Aki}>
            <p>
              <a href=''>Teaser</a>
            </p>
          </section>
        </article>
      </div>
    </>
  );
}
